### ISSUE TITLE
1.1 Cant launch out of dev environment 

### ISSUE THREAD

**Issue by BluePhoenixLOL** [FrozenBlock/WilderWild#107]
Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod wilderwild
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:439)
	... 3 more

**Comment by MerpisMe** [comment]
adding consensus because we still need confirmation from at least one other

**Comment by AViewFromTheTop** [comment]
I can launch it

**Comment by BluePhoenixLOL** [comment]
when i use the jar i cant

**Comment by Osmiooo** [comment]
skill issue

**Comment by AViewFromTheTop** [comment]
> you have to check to make sure it's building the correct version. treetrain's had that issue a few times when building the jar for releases

why wouldn't it build the right version

**Comment by MerpisMe** [comment]
> > you have to check to make sure it's building the correct version. treetrain's had that issue a few times when building the jar for releases
> 
> why wouldn't it build the right version

idk ask treetrain
i'm assuming it's an intellij moment
