### ISSUE TITLE
Incompatible with litematica

### ISSUE THREAD

**Issue by UsernameNotActive** [FrozenBlock/WilderWild#204]
It causes litematica to crash the world when joining. From what I can tell of the crash report, it has something to do with the custom biomes. I reported this issue to the litematica github, and he said that the issue should be fixed on your sides of things.

Mod version: Wilder Wild 1.1.9-Fabric+1.19.3
                      Litematica 0.13.1

Crash report:
java.lang.IllegalStateException: Errors during registry creation
	at net.minecraft.class_7877$class_7878.method_46798(class_7877.java:137)
	at net.minecraft.class_7877.method_46780(class_7877.java:265)
	at net.minecraft.class_7887.method_46817(class_7887.java:84)
	at fi.dy.masa.litematica.world.SchematicWorldHandler.createSchematicWorld(SchematicWorldHandler.java:40)
	at fi.dy.masa.litematica.world.SchematicWorldHandler.getSchematicWorld(SchematicWorldHandler.java:25)
	at fi.dy.masa.litematica.util.RayTraceUtils.traceToSchematicWorld(RayTraceUtils.java:339)
	at fi.dy.masa.litematica.util.RayTraceUtils.getGenericTrace(RayTraceUtils.java:366)
	at fi.dy.masa.litematica.render.OverlayRenderer.renderHoverInfo(OverlayRenderer.java:462)
	at fi.dy.masa.litematica.event.RenderHandler.onRenderGameOverlayPost(RenderHandler.java:52)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderGameOverlayPost(RenderEventHandler.java:68)
	at net.minecraft.class_329.handler$ccl000$onGameOverlayPost(class_329.java:3490)
	at net.minecraft.class_329.method_1753(class_329.java:396)
	at net.minecraft.class_757.method_3192(class_757.java:910)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:jellyfish_caves]
		at net.minecraft.class_7877$class_7878.method_46797(class_7877.java:128)
		at net.minecraft.class_7877.method_46780(class_7877.java:264)
		... 18 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:cypress_wetlands]
		at net.minecraft.class_7877$class_7878.method_46797(class_7877.java:128)
		at net.minecraft.class_7877.method_46780(class_7877.java:264)
		... 18 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:mixed_forest]
		at net.minecraft.class_7877$class_7878.method_46797(class_7877.java:128)
		at net.minecraft.class_7877.method_46780(class_7877.java:264)
		... 18 more

**Comment by AViewFromTheTop** [comment]
What the heck

**Comment by AViewFromTheTop** [comment]
this might be fixed in 2.0.
for now i'm marking this as awaiting response until 2.0's released.

**Comment by Treetrain1** [comment]
> this might be fixed in 2.0. for now i'm marking this as awaiting response until 2.0's released.

I've already fixed it.
It's not our issue.

I submitted a PR to litematica and its already been merged

**Comment by AViewFromTheTop** [comment]
> > this might be fixed in 2.0. for now i'm marking this as awaiting response until 2.0's released.
> 
> I've already fixed it. It's not our issue.
> 
> I submitted a PR to litematica and its already been merged

Yoooo

**Comment by AViewFromTheTop** [comment]
In that case I’ll be closing this
