### ISSUE TITLE
Crash on Opening Inventory 23w05a

### ISSUE THREAD

**Issue by TheDraconicAge** [FrozenBlock/WilderWild#206]
**Description of the Bug Encountered**
Game crash when inventory is opened.

**Steps To Reproduce**
1. Make a world
2. Open the inventory
3. Boom

**Expected Behavior**
Actually opening the inventory

**Screenshots**
N/A

**Logs**
The game crashed whilst unexpected error
Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_514 failed
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2023-02-04 16:03:40
Description: Unexpected error

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_514 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_513.<init>(class_513.java:45)
	at net.minecraft.class_507.<init>(class_507.java:71)
	at net.minecraft.class_490.<init>(class_490.java:33)
	at net.minecraft.class_310.method_1508(class_310.java:1997)
	at net.minecraft.class_310.method_1574(class_310.java:1867)
	at net.minecraft.class_310.method_1523(class_310.java:1158)
	at net.minecraft.class_310.method_1514(class_310.java:789)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 16 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [nbtcrafting.mixins.json:client.MixinAnimatedResultButton from mod nbtcrafting] from phase [DEFAULT] in config [nbtcrafting.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 19 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on beforeItemDrawn could not find any targets matching 'Lnet/minecraft/class_514;method_25359(Lnet/minecraft/class_4587;IIF)V' in net.minecraft.class_514. Using refmap nbtcrafting-refmap.json [PREINJECT Applicator Phase -> nbtcrafting.mixins.json:client.MixinAnimatedResultButton from mod nbtcrafting -> Prepare Injections ->  -> handler$znm000$beforeItemDrawn(Lnet/minecraft/class_4587;IIFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_310;IIZLnet/minecraft/class_4587;Ljava/util/List;Lnet/minecraft/class_1799;I)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at jdk.internal.reflect.GeneratedConstructorAccessor60.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_513.<init>(class_513.java:45)
	at net.minecraft.class_507.<init>(class_507.java:71)
	at net.minecraft.class_490.<init>(class_490.java:33)
	at net.minecraft.class_310.method_1508(class_310.java:1997)

-- Affected level --
Details:
	All players: 1 total; [class_746['Draws4'/125, l='ClientLevel', x=-243.82, y=74.00, z=67.54]]
	Chunk stats: 1849, 877
	Level dimension: minecraft:overworld
	Level spawn location: World: (-256,88,64), Section: (at 0,8,0 in -16,5,4; chunk contains blocks -256,-64,64 to -241,319,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 637 game time, 637 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2393)
	at net.minecraft.class_310.method_1514(class_310.java:813)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 23w05a
	Minecraft Version ID: 23w05a
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 873553560 bytes (833 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 2.69
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA Quadro K2100M
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x11fc
	Graphics card #0 versionInfo: DriverVersion=25.21.14.2650
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 1.60
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 1.60
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 32187.11
	Virtual memory used (MB): 24799.78
	Swap memory total (MB): 15872.00
	Swap memory used (MB): 1802.74
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.73.4+1.19.4
			fabric-api-base: Fabric API Base 0.4.23+ae26bc3517
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.22+49abcf7e17
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.2+a1ccd7bf17
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d117
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.32+c6af733c17
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.14+1134c5b817
			fabric-command-api-v1: Fabric Command API (v1) 1.2.24+f71b366f17
			fabric-command-api-v2: Fabric Command API (v2) 2.2.3+3fc4752e17
			fabric-commands-v0: Fabric Commands (v0) 0.2.41+df3654b317
			fabric-containers-v0: Fabric Containers (v0) 0.1.49+df3654b317
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.4+1d37d50217
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.4+8e4e694f17
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebe17
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.2.3+12a6ba2c17
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.43+48349a3f17
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.10+12a6ba2c17
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.42+a1ccd7bf17
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.47+df3654b317
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.32+a1ccd7bf17
			fabric-item-api-v1: Fabric Item API (v1) 2.1.13+12a6ba2c17
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.15+1134c5b817
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.32+c477957e17
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.30+df3654b317
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.12+23a79c8a17
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.23+75e9821117
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.27+9e7660c617
			fabric-message-api-v1: Fabric Message API (v1) 5.0.16+6ede1da917
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.34+49abcf7e17
			fabric-models-v0: Fabric Models (v0) 0.3.29+11ba9c3b17
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.19+c477957e17
			fabric-networking-v0: Fabric Networking (v0) 0.3.36+df3654b317
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.3+81af046e17
			fabric-particles-v1: Fabric Particles (v1) 1.0.22+f1e4495b17
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.3+a1ccd7bf17
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.7+a1ccd7bf17
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.3+9f179aa117
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.3+9f179aa117
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.33+df3654b317
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.27+afca2f3e17
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.20+f1e4495b17
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.36+df3654b317
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.4+12a6ba2c17
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.3+1134c5b817
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.8+12a6ba2c17
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.43+f1e4495b17
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.15+a1ccd7bf17
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e9821117
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.17+ccd377ba17
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.3+12a6ba2c17
		fabricloader: Fabric Loader 0.14.14
		frozenlib: FrozenLib 1.1.11-Fabric+23w04a
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.4-alpha.23.5.a
		wilderwild: Wilder Wild 1.1.10-Fabric+23w04a
			caffeineconfig: CaffeineConfig 1.0.0+1.17
			nbtcrafting: NBT Crafting 2.2.3+mc23w04a
	Launched Version: fabric-loader-0.14.14-23w05a
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Quadro K2100M/PCIe/SSE2 GL version 3.2.0 NVIDIA 426.50, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: fabric
	Current Language: en_us
	CPU: 8x Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Draws4'/125, l='ServerLevel[Crash]', x=-243.82, y=74.00, z=67.54]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Additional context**
Possibly connected to version disparity between 23w04a and 23w05a, despite lack of relevant backend changes.

**Comment by Treetrain1** [comment]
We do not support 23w05a at the moment.
It is being worked on but there is no ETA for it to be finished.

**Comment by Treetrain1** [comment]
A build for 23w05a has been released.
