### ISSUE TITLE
incompatible with twigs - baobab nuts freeze the server - net.frozenblock.wilderwild.block.BaobabNutBlock.method_9530(BaobabNutBlock.java:78)

### ISSUE THREAD

**Issue by stunlocked1** [FrozenBlock/WilderWild#252]
To reproduce, install WilderWild, Twigs, and Fabric API;
give yourself a baobab nut;
plant it and bonemeal it;
it freezes the server, you can move but mobs are frozen, blocks don't drop items, etc. You can't exit either, it gets stuck on the saving world screen potentially corrupting the world. Can only kill minecraft via task manager.

log - https://gist.github.com/stunlocked1/cdab877b436816551ad90aa46981d8f0
threads dump after it froze - https://gist.github.com/stunlocked1/684ebd1c32fa6a5fb753b50518fc67a3

specifically this one seems to be causing the issue
```
"Worker-Main-8" #48 daemon prio=5 os_prio=0 cpu=83062.50ms elapsed=632.26s tid=0x000001bb3487b060 nid=0x4adc waiting on condition  [0x00000030211fe000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.7/Native Method)
        - parking to wait for  <0x0000000674600000> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.util.concurrent.locks.LockSupport.park(java.base@17.0.7/LockSupport.java:211)
        at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.7/CompletableFuture.java:1864)
        at java.util.concurrent.ForkJoinPool.compensatedBlock(java.base@17.0.7/ForkJoinPool.java:3449)
        at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.7/ForkJoinPool.java:3432)
        at java.util.concurrent.CompletableFuture.waitingGet(java.base@17.0.7/CompletableFuture.java:1898)
        at java.util.concurrent.CompletableFuture.join(java.base@17.0.7/CompletableFuture.java:2117)
        at net.minecraft.class_3215.method_12121(class_3215.java:122)
        at net.minecraft.class_1937.method_8402(class_1937.java:197)
        at net.minecraft.class_4538.method_22342(class_4538.java:156)
        at net.minecraft.class_1937.method_8497(class_1937.java:191)
        at net.minecraft.class_1937.method_8320(class_1937.java:369)
        at net.minecraft.class_4970$class_4971.handler$zoc000$twigs$removeOffset(class_4970.java:1159)
        at net.minecraft.class_4970$class_4971.method_26226(class_4970.java)
        at net.frozenblock.wilderwild.block.BaobabNutBlock.method_9530(BaobabNutBlock.java:78)
        at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:856)
        at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:852)
        at net.minecraft.class_4970.method_9571(class_4970.java:283)
        at net.minecraft.class_4970$class_4971.method_26201(class_4970.java:752)
        at net.minecraft.class_4970$class_4971.method_26216(class_4970.java:838)
        at net.minecraft.class_4970.method_9505(class_4970.java:301)
        at net.minecraft.class_4970$class_4971.method_26193(class_4970.java:740)
        at net.minecraft.class_3558.method_20479(class_3558.java:98)
        at net.minecraft.class_3572.method_15488(class_3572.java:34)
        at net.minecraft.class_3554.method_15484(class_3554.java:175)
        at net.minecraft.class_3572.method_15487(class_3572.java:111)
        at net.minecraft.class_3554.method_15492(class_3554.java:216)
        at net.minecraft.class_3558.method_15516(class_3558.java:193)
        at net.minecraft.class_3568.method_15516(class_3568.java:65)
        at net.minecraft.class_3227.method_14277(class_3227.java:188)
        at net.minecraft.class_3227.method_17313(class_3227.java:107)
        at net.minecraft.class_3227$$Lambda$7309/0x00000008019f0a90.run(Unknown Source)
        at net.minecraft.class_3900.method_17634(class_3900.java:62)
        at net.minecraft.class_3900$$Lambda$7001/0x000000080199e000.run(Unknown Source)
        at net.minecraft.class_3846.method_16907(class_3846.java:91)
        at net.minecraft.class_3846.method_16900(class_3846.java:146)
        at net.minecraft.class_3846.run(class_3846.java:102)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(java.base@17.0.7/ForkJoinTask.java:1395)
        at java.util.concurrent.ForkJoinTask.doExec(java.base@17.0.7/ForkJoinTask.java:373)
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@17.0.7/ForkJoinPool.java:1182)
        at java.util.concurrent.ForkJoinPool.scan(java.base@17.0.7/ForkJoinPool.java:1655)
        at java.util.concurrent.ForkJoinPool.runWorker(java.base@17.0.7/ForkJoinPool.java:1622)
        at java.util.concurrent.ForkJoinWorkerThread.run(java.base@17.0.7/ForkJoinWorkerThread.java:165)

   Locked ownable synchronizers:
        - None
```
also I've noticed that without twigs it doesn't freeze the ticks, but i kept bonemealing the baobab nut and it never grew

**Comment by DasBlackfur** [comment]
Can confirm! This also happens in some cases when pregenerating a world with chunky. It simply hanged the server. I was only able to debug this with modernfixes chunk loading debugger.
I will attempt to create a PR with a fix to the nuts.

**Comment by mateus3c** [comment]
can confirm too

**Comment by AViewFromTheTop** [comment]
why the heck are baobab nuts causing so many issues lmao im so confused-
@DasBlackfur since you mentioned a PR, do you happen to have any insight as to what’s actually going on? I’m surprised this isn’t an issue with Coconuts as well as they’re mostly similar to Baobab Nuts. Biggest difference is just how many you need planted to grow them (4x4, I may change it to 2x2 since many people are having issues with it)

**Comment by mateus3c** [comment]
@AViewFromTheTop take a look at the other issue I opened, I posted my entire log file, maybe your able to find out whats the issue comparing mine with this one here?

**Comment by DasBlackfur** [comment]
@AViewFromTheTop IntelliJ yells at me in confusion when I even open the Boabab Nut class, I did not have much time to look into it, but I am still searching.

**Comment by AViewFromTheTop** [comment]
Since nobody's offered any updates I will be closing this issue.
