### ISSUE TITLE
Terra incompatibility

### ISSUE THREAD

**Issue by Poly2it** [FrozenBlock/WilderWild#258]
This crash has returned. I am experiencing the same issue on the latest release ([2.0.6](https://modrinth.com/mod/wilder-wild/version/2.0.6-mc1.19.2)).

_Originally posted by @Poly2it in https://github.com/FrozenBlock/WilderWild/issues/226#issuecomment-1614805900_

**Comment by Poly2it** [comment]
I am able to provide some more context: this issue occurs on 2.0.X release.

**Comment by Poly2it** [comment]
```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-06-30 17:52:14
Description: Initializing game

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3037.method_30649()" because "this.comp_333" is null
	at net.minecraft.class_2975.method_30648(class_2975.java:31)
	at net.minecraft.class_6796.method_39643(class_6796.java:67)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at net.minecraft.class_5485.method_40140(class_5485.java:58)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at net.minecraft.class_5485.method_30982(class_5485.java:67)
	at com.dfsek.terra.mod.util.MinecraftUtil.lambda$registerFlora$0(MinecraftUtil.java:75)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196)
	at com.dfsek.terra.mod.util.MinecraftUtil.lambda$registerFlora$2(MinecraftUtil.java:71)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.dfsek.terra.mod.util.MinecraftUtil.lambda$registerFlora$3(MinecraftUtil.java:70)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196)
	at com.dfsek.terra.mod.util.MinecraftUtil.lambda$registerFlora$5(MinecraftUtil.java:69)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at com.dfsek.terra.mod.util.MinecraftUtil.registerFlora(MinecraftUtil.java:67)
	at com.dfsek.terra.lifecycle.util.BiomeUtil.registerBiomes(BiomeUtil.java:38)
	at com.dfsek.terra.lifecycle.util.LifecycleUtil.initialize(LifecycleUtil.java:16)
	at net.minecraft.class_310.handler$fei000$terra$injectConstructor(class_310.java:23471)
	at net.minecraft.class_310.<init>(class_310.java:484)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2975.method_30648(class_2975.java:31)
	at net.minecraft.class_6796.method_39643(class_6796.java:67)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at net.minecraft.class_5485.method_40140(class_5485.java:58)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at net.minecraft.class_5485.method_30982(class_5485.java:67)
	at com.dfsek.terra.mod.util.MinecraftUtil.lambda$registerFlora$0(MinecraftUtil.java:75)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196)
	at com.dfsek.terra.mod.util.MinecraftUtil.lambda$registerFlora$2(MinecraftUtil.java:71)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.dfsek.terra.mod.util.MinecraftUtil.lambda$registerFlora$3(MinecraftUtil.java:70)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196)
	at com.dfsek.terra.mod.util.MinecraftUtil.lambda$registerFlora$5(MinecraftUtil.java:69)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at com.dfsek.terra.mod.util.MinecraftUtil.registerFlora(MinecraftUtil.java:67)
	at com.dfsek.terra.lifecycle.util.BiomeUtil.registerBiomes(BiomeUtil.java:38)
	at com.dfsek.terra.lifecycle.util.LifecycleUtil.initialize(LifecycleUtil.java:16)
	at net.minecraft.class_310.handler$fei000$terra$injectConstructor(class_310.java:23471)
	at net.minecraft.class_310.<init>(class_310.java:484)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.19.0-46-generic
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 508318824 bytes (484 MiB) / 1207959552 bytes (1152 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i5-13600K
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 5.10
	Number of physical packages: 1
	Number of physical CPUs: 14
	Number of logical CPUs: 20
	Graphics card #0 name: GA106 [GeForce RTX 3060 Lite Hash Rate]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 16416.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 17999.42
	Virtual memory used (MB): 12229.18
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 0.00
	JVM Flags: 8 total; -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced-tooltips: Advanced Tooltips 1.6.0+1.19
			advanced-tooltips-core: Advanced Tooltips Core 1.6.0
		amecs: Amecs 1.3.8+mc.1.19-rc2
			amecsapi: Amecs API 1.3.6+mc22w17a
		architects_palette: Architect's Palette Fabric 2.1.1
		architectury: Architectury 6.5.69
		automobility: Automobility 0.4.2+1.19.2-fabric
			jsonem: JsonEM 0.1.3+1.19
		bedrockify: BedrockIfy 1.5.1+mc1.19.1
		bedspreads: Bedspreads 6.0.0+1.19.2
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.2
			org_reflections_reflections: reflections 0.10.2
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.0
		betterpotionvisuals: Better Potion Visuals 1.0.0
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		boathud: BoatHud 1.1.2
		bobby: Bobby 4.0.1
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.9.9
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.9.9
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.9.9
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.9.9
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.9.9
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.9.9
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.9.9
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.9.9
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.9.9
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.9.9
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.9.9
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.9.9
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.9.9
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.9.9
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.9.9
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.9.9
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.9.9
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.9.9
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.9.9
			c2me-threading-scheduling: Concurrent Chunk Management Engine (Threading/Scheduling) 0.2.0+alpha.9.9
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.9.9
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		cakechomps: Cake Chomps 6.0.0+1.19.2
		cherishedworlds: Cherished Worlds 6.0.5+1.19.4
		chime: Chime 1.3.0
		chunksfadein: Chunks Fade In 3.0.11-1.19
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		citresewn: CIT Resewn 1.1.2+1.19.2
			citresewn-defaults: CIT Resewn: Defaults 1.1.2+1.19.2
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		computercraft: CC: Restitched 1.101.2
			io_netty_netty-codec-http: netty-codec-http 4.1.77.Final
			org_squiddev_cobalt: Cobalt 0.5.5
		continuity: Continuity 2.0.1+1.19
		coppertier: Copper Tier 1.0
		create: Create 0.5.1-b-build.1079+mc1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.8.a-5
			forgeconfigapiport: Forge Config API Port 4.2.9
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			porting_lib: Porting Lib 2.1.1032+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_accessors: Porting Lib Accessors 2.1.1032+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.1032+1.19.2
				porting_lib_base: Porting Lib Base 2.1.1032+1.19.2
				porting_lib_common: Porting Lib Common 2.1.1032+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.1032+1.19.2
				porting_lib_entity: Porting Lib Entity 2.1.1032+1.19.2
				porting_lib_extensions: Porting Lib Extensions 2.1.1032+1.19.2
				porting_lib_fake_players: Porting Lib Fake Players 2.1.1032+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1032+1.19.2
				porting_lib_loot: Porting Lib Loot 2.1.1032+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1032+1.19.2
				porting_lib_model_loader: Porting Lib Model Loader 2.1.1032+1.19.2
				porting_lib_models: Porting Lib Models 2.1.1032+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.1032+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1032+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.1032+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			registrate-fabric: Registrate for Fabric 1.1.58-MC1.19.2
		crittersandcompanions: Critters and Companions 1.19.2-2.0.1
		customizableelytra: Customizable Elytra 1.6.4-1.19
		dark-enchanting: Dark Enchanting 1.0.0+1.19.1
			libgui: LibGui 6.0.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
			omega-config: OmegaConfig 1.2.3-1.18.1
		dynamicfps: Dynamic FPS 2.2.0
		emi: EMI 1.0.5+1.19.2+fabric
		emi_loot: EMI Loot 0.6.4+1.19
		emitrades: EMI Trades 1.0.2+mc1.19.2
		enchantedshulkers: Enchanted Shulkers 1.0.4
			mm: Manningham Mills 2.3
		enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			spruceui: SpruceUI 4.0.0+1.19
		entity_texture_features: Entity Texture Features 4.4.4
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entitycollisionfpsfix: Entity Collision FPS Fix 2.0.0.0
		entityculling: EntityCulling-Fabric 1.6.1-mc1.19.2
		fabric-api: Fabric API 0.76.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.8+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.9.1+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.19.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.21
		ferritecore: FerriteCore 5.0.3
		flowerpatch: Flower Patch 2.0.2
		geckolib3: Geckolib 3.1.40
			com_eliotlash_mclib_mclib: mclib 20
		glassbreaker: Glass Breaker 1.0.2
		here-be-no-dragons: Here be no Dragons! 1.0.0
		horsebuff: HorseBuff 2.0.1
		iknowwhatimdoing: I Know What I'm Doing 4.1.1
		illagerexp: Illager Expansion [Rematch] 1.0.0
		immediatelyfast: ImmediatelyFast 1.1.12
			net_lenni0451_reflect: Reflect 1.1.0
		immersive_weathering: Immersive Weathering 1.19.2-1.2.9
		indium: Indium 1.0.9+mc1.19.2
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		isnrmn: Item Suggestions Not Require Mod Name v1_03
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		kubejs: KubeJS 1902.6.0-build.142
		languagereload: Language Reload 1.5.8+1.19.2
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.11.1
		memoryleakfix: Memory Leak Fix 1.1.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
		microdurability: microDurability 0.3.6+1.19
			microdurability-core: microDurability Core 0.3.6
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.2.0-beta.2
		moonlight: Moonlight 1.19.2-2.2.27
		morecreativetabs: MoreCreativeTabs 1.2.1
		moreculling: More Culling 1.19.1-0.17.0
			conditional-mixin: conditional mixin 0.3.0
		moremobvariants: More Mob Variants 1.0.1
		nochatreports: No Chat Reports 1.19.2-v1.13.12
		noenchantcap: No Enchant Cap 2.2.4
		passivepregen: Passive Chunk Pregenerator 1.0.3
		pathunderfencegates: Path Under Fence Gates 1.3.0
		paxi: Paxi 1.19.2-Fabric-3.0.1
		quicksort: Quicksort 0.2.0+1.19.2
		radon: Radon 0.3.3
		recipedisable: Recipedisable 1.3.2
			com_github_nerjalnosk_jsonlight: JsonLight 1.4.0
		rhino: Rhino 1902.2.2-build.268
		simpleshulkerpreview: Simple Shulker Preview 2.1
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		starlight: Starlight 1.1.1+fabric.ae22326
		terra: Terra 6.2.1-BETA+358e09d05
			cloud: Cloud 1.7.0
				cloud_commandframework_cloud-brigadier_: cloud-brigadier 1.7.0
				cloud_commandframework_cloud-core_: cloud-core 1.7.0
				cloud_commandframework_cloud-services_: cloud-services 1.7.0
				fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		trinkets: Trinkets 3.4.2
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
		vanityslots: Vanity Slots 1.2.8
		villager-hats: Villager Hats 1.4.3
		vt_downloader: VTDownloader 2.0.0
		wilderwild: Wilder Wild 2.0.6-Fabric+1.19.2
			caffeineconfig: CaffeineConfig 1.0.0+1.17
			frozenlib: FrozenLib 1.2.6-Fabric+1.19.2
				blue_endless_jankson: jankson 1.2.2
			nbtcrafting: NBT Crafting 2.2.3+mc1.19
		windchimes: Windchimes 1.2.1
		yet-another-config-lib: YetAnotherConfigLib 2.2.0-for-1.19.2
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.9
			org_javassist_javassist: javassist 3.28.0-GA
		zoomify: Zoomify 2.9.0
			dev_isxander_settxi_settxi-core: settxi-core 2.10.5
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.5
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.5
			settxi-gui-yacl: Settxi Gui (YetAnotherConfigLib) 2.10.5
	Flywheel Backend: Uninitialized
	Launched Version: fabric-loader-0.14.21-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

**Comment by Treetrain1** [comment]
does the crash occur without wilder wild?

**Comment by Poly2it** [comment]
> does the crash occur without wilder wild?

No

**Comment by Poly2it** [comment]
@Treetrain1, are you able to validate that this is a crash?

**Comment by AViewFromTheTop** [comment]
@Treetrain1 do you think we should maybe switch out your getHolder thing for the usual placed/configuredFeatures.getOrThrow() thing and ask them to test it out?
that would require… a lot of work, but if it solves the problem at least you know something needs to be changed

**Comment by AViewFromTheTop** [comment]
At the same time though isn’t that a datagen only thing..?? so maybe not
I’m so confused lol

**Comment by Poly2it** [comment]
> @Treetrain1 do you think we should maybe switch out your getHolder thing for the usual placed/configuredFeatures.getOrThrow() thing and ask them to test it out? that would require… a lot of work, but if it solves the problem at least you know something needs to be changed

Sure, I appreciate the effort.

**Comment by AViewFromTheTop** [comment]
@Poly2it by any chance did you downlaod frozenlib as a separate mod?
if so, could you test with that deleted?

**Comment by Poly2it** [comment]
> @Poly2it by any chance did you downlaod frozenlib as a separate mod? if so, could you test with that deleted?

I did not.

**Comment by Treetrain1** [comment]
as far as i can tell its a compatibility issue with the Terra mod

**Comment by AViewFromTheTop** [comment]
Does this still happen?

**Comment by AViewFromTheTop** [comment]
I'll be closing this as no response has been given.
