### ISSUE TITLE
Minecraft freezes and falls on my modpack

### ISSUE THREAD

**Issue by SpiritOTHawk** [FrozenBlock/WilderWild#272]
**Description of the Bug Encountered**
Minecraft freezes and falls on my modpack when I update the WilderWild until the last version of it

**Steps To Reproduce**
1. Instal my modpack (https://modrinth.com/modpack/adventuretime)
2. Install latest version of WilderWild
3. Go to deepdark biome
4. Wait

**Logs**
```
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: Caused by: net.minecraft.class_148: Feature placement
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2794.method_12102(class_2794.java:377)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2806.method_51375(class_2806.java:108)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2806.md0f253a$c2me-threading-worldgen$lambda$runGenerationTask$0$5(class_2806.java:1608)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	... 3 more
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: Caused by: java.lang.ClassCastException: class net.minecraft.class_3233 cannot be cast to class net.minecraft.class_2338 (net.minecraft.class_3233 and net.minecraft.class_2338 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @7dc7cbad)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_7125.args$jma000$wilderwild$wilderWild$newPlace(class_7125.java:1204)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_7125.method_41471(class_7125.java:38)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_7128$class_7129.method_41499(class_7128.java:246)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_7128.method_41479(class_7128.java:357)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_7140.method_13151(class_7140.java:40)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2975.method_12862(class_2975.java:537)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_6796.method_39646(class_6796.java:54)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_6796.method_39648(class_6796.java:53)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_6796.method_39650(class_6796.java:42)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2794.method_12102(class_2794.java:357)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	... 7 more
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: Caused by: net.minecraft.class_148: Feature placement
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2794.method_12102(class_2794.java:377)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2806.method_51375(class_2806.java:108)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2806.md0f253a$c2me-threading-worldgen$lambda$runGenerationTask$0$5(class_2806.java:1608)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	... 3 more
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: Caused by: java.lang.ClassCastException: class net.minecraft.class_3233 cannot be cast to class net.minecraft.class_2338 (net.minecraft.class_3233 and net.minecraft.class_2338 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @7dc7cbad)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_7125.args$jma000$wilderwild$wilderWild$newPlace(class_7125.java:1204)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_7125.method_41471(class_7125.java:38)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_7128$class_7129.method_41499(class_7128.java:246)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_7128.method_41479(class_7128.java:357)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_7140.method_13151(class_7140.java:40)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2975.method_12862(class_2975.java:537)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_6796.method_39646(class_6796.java:54)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_6796.method_39648(class_6796.java:53)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_6796.method_39650(class_6796.java:42)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2794.method_12102(class_2794.java:357)
[11:12:50] [C2ME worker #1/INFO]: [STDERR]: 	... 7 more
```
[2023-07-21-7.log.gz](https://github.com/FrozenBlock/WilderWild/files/12121576/2023-07-21-7.log.gz)

**Comment by Treetrain1** [comment]
Does this crash occur without C2ME?

**Comment by spoorn** [comment]
Happened to me too, I don't have C2ME installed, but I don't get any logs or crash report - it just freezes indefinitely.  I'm in singleplayer and watchdog isn't biting.

**Comment by AViewFromTheTop** [comment]
@Treetrain1 long story short, we're going to be looking for a mod that replaceslevel.setBlock(blockPos2, blockState, 3) in SculkBlock's attemptUseCharge() with a method with WorldGenRegion (likely just level) as the first parameter instead of blockPos
and i checked and no it isn't Sculk Depths

**Comment by AViewFromTheTop** [comment]
@SpiritOTHawk would you be able to try without the Lost Features mod?
If this solves the issue, this is unfortunately nothing on our side.
Lost Features uses Redirects in their Sculk mixins, while we use (and recommend) mixin extras instead, which can do the same thing without causing destructive action towards other mods.

**Comment by SpiritOTHawk** [comment]
> @SpiritOTHawk would you be able to try without the Lost Features mod?

Without Lost Features mod works fine.

**Comment by AViewFromTheTop** [comment]
> Without Lost Features mod works fine.

Alright.
This issue is entirely on their side in that case, I’d recommend you open up the issue for that mod instead.
The problem is that their Sculk Block Mixin uses Redirects, which are infamous for being destructive and causing incompatibilities with other mods.
I’d recommend that they look into MixinExtras (what we use) instead or perhaps use ModifyArgs, that way they can achieve their intended functionality without breaking other mods.
You can link this issue to them as well, I hope they’ll read this.

**Comment by Treetrain1** [comment]
going to close as this isnt our issue
