### ISSUE TITLE
Embedded Nbt Crafting causes packet issues

### ISSUE THREAD

**Issue by ethanhs** [FrozenBlock/WilderWild#299]
**Description of the Bug Encountered**
When I try to load into my world, I get the following exception right after the embedded library Nbt Crafting (which it seems you have forked to maintain) logs `[Nbt Crafting] Syncing advanced recipe data to player <playername>`:
```
[Nbt Crafting] Syncing advanced recipe data to player <playername>
[13:28:00] [Netty Epoll Server IO #2/ERROR]: Error receiving packet 109
java.lang.IllegalArgumentException: Packet too big (is 8566384, should be less than 8388608): net.minecraft.class_2788@33474313
        at net.minecraft.class_2545.method_10838(class_2545.java:48) ~[server-intermediary.jar:?]
        at net.minecraft.class_2545.encode(class_2545.java:14) ~[server-intermediary.jar:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.82.Final.jar:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.82.Final.jar:?]
        at net.minecraft.class_2535.method_36942(class_2535.java:220) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10761(class_2535.java:212) ~[server-intermediary.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Steps To Reproduce**
I'm not sure of exact steps, it is likely due to a very large modpack with many mods adding recipes.

<details>
<summary>Full mod list</summary>

```
[13:54:54] [main/INFO]: Loading 462 mods:
	- abverticaledition 1.0.3-b
	- additionallanterns 1.0.4-a
	- additionalstructures 4.2.0
	- adorn 5.0.0+1.20.1
	- advancednetherite 2.0.2-1.20.1
	- aki 1.3
	- allstackable v2.0.0-1.20.1
	- allthetrims 3.2.5
	   |-- com_github_llamalad7_mixinextras 0.2.0-beta.10
	   \-- mixinsquared 0.0.1
	- alwaysinfectmod 1.20.1-1.0.1
	- ambientsounds 5.2.22
	- amplified_nether 1.2.2
	- animal_feeding_trough 1.0.3+1.20.1
	- antighost 1.20-fabric0.83.0-1.1.5
	   \-- crowdin-translate 1.4+1.19.3
	- appleskin 2.5.0+mc1.20
	- aqupdcaracal 1.20-2.3.3
	- aqupdgrizzly 1.20-1.6.1
	- archaeologybanners 5.0.3
	- archeologyplus 1.0.2
	- architectury 9.1.12
	- athena 3.1.0
	- awesomedungeon 3.2.0
	- awesomedungeonend 3.1.1
	- awesomedungeonocean 3.3.0
	- balm-fabric 7.0.7
	- bclib 3.0.13
	   \-- wunderlib 1.1.5
	- beachparty 1.1.2
	- beautify 1.0.0+1.20
	- bee_info 1.1.2
	- beekeeperhut 1.3.0
	- beenfo 1.20-fabric0.83.0-1.3.3
	   |-- crowdin-translate 1.4+1.19.3
	   \-- gbfabrictools 1.3.5+1.20
	- beproud 0.1.0
	- better-sign-edit 1.1.0
	- betteradvancements 0.3.2.161
	- betterarcheology 1.0.2
	- betterend 4.0.10
	- betterf3 7.0.1
	- betterlily 1.20-1.3.2
	- betternether 9.0.9
	- bettersafebed 1.20-8
	- bettertrims 1.4.0
	- bettervillage 3.1.0
	- biomemakeover 1.20.1-1.10.2
	   \-- taniwha 1.20.0-5.1.1
	- blahaj ${version}
	- blissful-butterflies 1.2.1
	- boatiview 0.0.5
	- bookshelf 20.0.3
	- bottledair 2.1
	- bowinfinityfix 2.6.0
	- brewinandchewin fabric-2.3.1+1.20.1
	   \-- mm 2.3
	- bushierflowers 0.0.3-1.20.1
	- cakedelight 1.20.1-v3.0.1
	- capymod 1.2
	- carpeted 1.20-1.4
	- cat_jam 1.1.3
	- chalk 2.2.0
	   \-- simplefabric 1.0.0
	- chalk-colorful-addon 2.1.1+1.19.3
	- charmofundying 6.4.2+1.20.1
	   \-- spectrelib 0.13.13+1.20.1
	        |-- com_electronwill_night-config_core 3.6.5
	        \-- com_electronwill_night-config_toml 3.6.5
	- chipped 3.0.1
	- chisel 1.6
	   \-- templates 2.1.1+1.20.1
	- chunky 1.3.92
	- cinderscapes 4.0.8
	   |-- biolith 1.0.0-alpha.8
	   |    \-- terraform-surfaces-api-v1 7.0.1
	   |-- cinderscapes-client 4.0.8
	   |-- cinderscapes-common 4.0.8
	   |-- cinderscapes-worldgen 4.0.8
	   |-- terraform-biome-remapper-api-v1 7.0.1
	   |-- terraform-shapes-api-v1 7.0.1
	   |-- terraform-surfaces-api-v1 7.0.1
	   \-- terraform-wood-api-v1 7.0.1
	- cloth-config 11.1.106
	   \-- cloth-basic-math 0.6.1
	- clutter 1.20-0.4.3
	- collective 6.65
	- colorbricks 1.20.1-1.2.3
	- colorize 1.6.0
	- compact_storage 5.0.3_1.20.1
	- companion 5.1.0
	- completeconfig 2.5.0
	   |-- completeconfig-base 2.5.0
	   |-- completeconfig-gui-cloth 2.5.0
	   \-- completeconfig-gui-yacl 2.5.0
	- connectedglass 1.1.7
	- connectiblechains 2.2.1+1.20.1
	- continuity 3.0.0-beta.3+1.20.1
	- cookingforblockheads 16.0.0
	- corndelight 1.0.3
	- cr-arrows-info 1.2.3+1.20
	- creativecore 2.10.28
	   \-- net_minecraftforge_eventbus 6.0.3
	- creeperoverhaul 3.0.1
	- creo 1.0.0-beta.21
	- cristellib 1.1.2
	- cryingportals 2.3
	- ctov 3.3.4
	- culturaldelights 0.14.9+1.20.1
	   \-- terraform-wood-api-v1 7.0.1
	- cupboard 1.20.1-1.7
	- customizableelytra 2.1.0+1.20
	- dawn 5.0.0
	   |-- terraform-shapes-api-v1 7.0.1
	   \-- terraform-wood-api-v1 7.0.1
	- deeperdarker fabric-1.20-1.2.0
	   \-- customportalapi 0.0.1-beta64-1.20
	- delightful-froge 0.1.0+1.20
	- diagonalfences 8.0.1
	- disable_enderman_picking_up_blocks 1.2
	- doapi 1.2.6
	   \-- terraform-wood-api-v1 7.0.1
	- dogslie 1.2.0
	- doubledoors 5.0
	- duckling 3.0.0
	- ducky-updater-lib 2023.7.2
	- dungeons_arise 2.1.56.1
	- dynamictrim 1.2.1
	- easyanvils 8.0.1
	- easyelytratakeoff 4.0
	- easymagic 8.0.1
	- elytraslot 6.3.0+1.20.1
	- emi 1.0.19+1.20.1+fabric
	- enchant_the_rainbow 1.3.0
	- enchantment_lore 1.3.2
	   |-- crowdin-translate 1.4+1.19.3
	   \-- server_translations_api 2.0.0+1.20
	        \-- packet_tweaker 0.4.0+1.19.4
	- endrem 5.2.2
	- ends_delight 1.0.1
	- entity_texture_features 4.5.1
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- entityculling 1.6.2-mc1.20
	- everycomp 1.20-2.6.3
	- exlineawnings 1.1.8
	- exlinefurniture 2.6.3
	- explorerscompass 1.20.1-2.2.2-fabric
	- explorify v1.3.0-mc1.20u1.20.1
	- extended_drawers 2.0.5+mc.1.20.1
	   |-- config_toolkit 1.0.0
	   |    |-- io_determann_shadow-api-17 0.1.1
	   |    \-- net_fabricmc_javapoet 0.1.0
	   |-- graphlib 1.1.1+1.20
	   |    |-- kmodlib-overlay 0.2.4+1.20
	   |    \-- libnetworkstack 0.10.0
	   |-- noindium 1.1.0+1.20
	   \-- yet_another_config_lib_v3 3.1.0+1.20
	        |-- com_twelvemonkeys_common_common-image 3.10.0-SNAPSHOT
	        |-- com_twelvemonkeys_common_common-io 3.10.0-SNAPSHOT
	        |-- com_twelvemonkeys_common_common-lang 3.10.0-SNAPSHOT
	        |-- com_twelvemonkeys_imageio_imageio-core 3.10.0-SNAPSHOT
	        |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0-SNAPSHOT
	        \-- com_twelvemonkeys_imageio_imageio-webp 3.10.0-SNAPSHOT
	- fabric-api 0.88.1+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
	   |-- fabric-block-api-v1 1.0.10+92a0d36777
	   |-- fabric-block-view-api-v2 1.0.0+92a0d36777
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.9+b3afc78b77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.2.2+1e61dba177
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.10+23d9108177
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.1.39+b3afc78b77
	   |-- fabric-loot-tables-v1 1.1.43+9e7660c677
	   |-- fabric-message-api-v1 5.1.7+3265161977
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.1+6beca84877
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.1.3+92a0d36777
	   |-- fabric-renderer-indigo 1.4.3+6bdb2ed077
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.1+195226a777
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabric-language-kotlin 1.10.10+kotlin.1.9.10
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.10
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.22.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.0
	- fabricloader 0.14.22
	- farmersdelight 1.20.1-1.4.2
	- farmersrespite 2.3.1
	- farsight 1.20.1-4.1
	   \-- org_jctools_jctools-core 4.0.1
	- fdjei 1.0.1
	- fennecfox 1.4.0
	- festive_delight 1.0.0
	- findme 3.1.0
	- fishofthieves 3.0.2
	- flighthelper 1.20-fabric0.83.0-1.2.2
	   \-- gbfabrictools 1.3.5+1.20
	- flowerpatch 3.0.0
	- flowerymooblooms 1.1.0
	- foodeffecttooltips 1.1.1-1.20.0
	- forgeconfigapiport 8.0.0
	- forgiveness 1.4.0
	- freecam 1.2.1+1.20
	- friendlyfire 18.0.3
	- friendsandfoes 1.9.4
	- frycmobvariants 4.2.2+1.20
	- fusion 1.0.5+a
	- gardens_of_the_dead 4.0.0
	- gazebo 1.0.1+1.20.1
	- geckolib 4.2.2
	   \-- com_eliotlash_mclib_mclib 20
	- glowing-torchflower 1.0.0
	- grass_kiss 1.20-fabric0.83.0-0.5.0
	- graveyard 2.9.1
	   \-- omega-config 1.2.2-1.18.1
	- great_big_world 1.2.7
	- handcrafted 3.0.1
	- harvestwithease 7.0.0.2
	- hidehands 4.0
	- hopobettermineshaft 1.1.8
	- hopobetterruinedportal 1.3.6
	- hopobetterunderwaterruins 1.1.3
	- hybrid-aquatic 1.0.1
	- immersive_paintings 0.6.5+1.20.1
	- imst 2.1.0
	- incendium 5.3.1
	- indium 1.0.25+mc1.20.1
	- indypets 1.2.3
	- infbanlay 1.2.0
	- infwithmend 1.0.2
	- inventoryprofilesnext 1.10.7
	- inventorytotem 3.0
	- iris 1.6.8
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- jade 11.5.1
	- jamlib 0.6.0+1.20
	- java 17
	- jei 15.2.0.27
	- jmc 1.13.1
	- jumpoverfences 1.0-SNAPSHOT
	- justoutdoorstuffs 1.0.2
	- kaffees_dual_ride 1.1.0
	- keepmysoiltilled 2.0
	- kiwi 11.1.1
	- kleeslabs 15.0.0
	- labels 1.20-1.16
	- leavemybarsalone 8.0.0
	- leavesbegone 8.0.0
	- libipn 4.0.0
	- libraryferret 4.0.0
	- litematica 0.15.3
	- livingthings 1.20.1-2.0.2
	- llamasteeds 2023.4.9
	- lootr 0.7.29.75
	- lovely_snails 1.1.3+1.20.1
	- malilib 0.16.0
	- mavapi 1.1.2
	- mavm 1.2.4
	- mbt 2.4.0-1.20.1
	- mcwbridges 2.1.0
	- mcwfences 1.0.7
	- mcwlights 1.0.6
	- mcwpaths 1.0.3
	- mcwroofs 2.2.4
	- mcwtrpdoors 1.1.1
	- measurements 2.0.0
	- mes 1.3-1.20-fabric
	- midnightlib 1.4.1
	- minecraft 1.20.1
	- minihud 0.27.0
	- mo_glass 1.6.1-MC1.20.1
	- modmenu 7.2.1
	- mooblooms 1.5.4
	- moonlight 1.20-2.8.16
	- more-axolotl 2.0.1
	- more_slabs_stairs_and_walls 3.0
	- morefrogs 1.20.1-1.2.5-fabric
	- moremobvariants 1.2.2
	- moreslabs 1.0
	- mr_dungeons_andtaverns 1-v2.1.4
	- mr_smelting_plus 1.0.4
	- mru 0.2.1+1.20
	- mvs 4.0-1.20-fabric
	- mythicupgrades +fabric-1.8.2-1.20.1
	- naturescompass 1.20.1-2.2.1-fabric
	- netherdepthsupgrade fabric-3.1.0-1.20
	- nightlights 1.1
	- noexpensive 1.20.1-1.9.0
	- npcvariety 2.3.0
	- nyctophobia 1.9
	   \-- omega-config 1.2.2-1.18.1
	- obsidianboat 3.0.2+mc1.20.1
	- oceansdelight fabric-1.0.2-1.20
	- overpoweredmending 2.12.0
	- owo 0.11.1+1.20
	- pack_it_up 0.3.1+1.20.1
	- patchouli 1.20.1-81-FABRIC
	   \-- fiber 0.23.0-2
	- perfectplushies 1.0.2
	- pet-armor 1.1-1.20.1
	- philipsruins 1.20.1
	- platforms 1.20.1-1.0
	- player-animator 1.0.2-rc1+1.20
	- plentyplates 8.0.0
	- plushables 1.1.2
	- plushies 1.3.0
	- polymorph 0.49.0+1.20.1
	   |-- cardinal-components-base 5.2.1
	   |-- cardinal-components-block 5.2.1
	   |-- cardinal-components-entity 5.2.1
	   |-- cardinal-components-item 5.2.1
	   \-- spectrelib 0.13.13+1.20.1
	        |-- com_electronwill_night-config_core 3.6.5
	        \-- com_electronwill_night-config_toml 3.6.5
	- potionparticlepack 1.0.1
	   |-- cardinal-components-base 5.2.1
	   \-- cardinal-components-entity 5.2.1
	- pridefishinglines 2.0.1+1.20.x
	- pridefurnaces 1.0.1+1.20
	- pridemoths 1.3.2
	- primalstorage 1.3
	- profundis 1.6.0
	- pumpeddesertfabric 1.0.0
	- puzzle 1.5.2+1.20
	   |-- puzzle-base 1.5.2+1.20
	   |-- puzzle-gui 1.5.2+1.20
	   |-- puzzle-models 1.5.2+1.20
	   \-- puzzle-splashscreen 1.5.2+1.20
	- puzzleslib 8.0.24
	- rainglow 1.1.2+mc1.20.1
	   \-- spruceui 5.0.0+1.20
	- randomsheepcolours 3.1
	- realisticbees 3.4
	- rechiseled 1.1.2
	- recipe-unlocker 1.0.1
	- reeses-sodium-options 1.6.5+mc1.20.1-build.95
	- regions_unexplored 0.4.1+1.20.1
	- repurposed_structures 7.1.5+1.20.1-fabric
	- resourcefulconfig 2.1.0
	- resourcefullib 2.1.10
	   |-- com_teamresourceful_bytecodecs 1.0.2
	   \-- com_teamresourceful_yabn 1.0.3
	- retraining 1.3.0
	- riverredux 0.3.1
	- scaffoldingdropsnearby 3.0
	- securecrops 1.0.4+1.20
	- shetiphiancore 1.20.1-1.0
	- showmeyourskin 1.6.11+1.20
	   |-- cardinal-components-base 5.2.1
	   |-- cardinal-components-entity 5.2.1
	   \-- cicada 0.4.0
	- shulkerboxslot 5.1.0+1.20.1
	   |-- cardinal-components-item 5.2.1
	   \-- spectrelib 0.13.13+1.20.1
	        |-- com_electronwill_night-config_core 3.6.5
	        \-- com_electronwill_night-config_toml 3.6.5
	- shulkerboxtooltip 4.0.4+1.20.1
	- sit 1.0.2+1.20-1.20.1
	- skeletalremains 1.4.1
	- skinlayers 1.5.4-mc1.20.1
	- skyvillages 1.0.2.1-1.20.1
	- smart-villagers-follow-emeralds 1.0.0
	- snifferplus 0.2.0
	- snowysniffer 1.0.0
	- sodium 0.5.2
	- sodium-extra 0.5.1+mc1.20.1-build.112
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- sound_physics_remastered 1.20.1-1.2.1
	- spell_engine 0.9.31+1.20.1
	- spell_power 0.9.17+1.20.1
	- splitshulkers 1.0.0
	- srias_flowers 3.0.0
	- stackablepotions 1.0.0
	- stackrefill 4.0
	- stoneworks 8.0.0
	- structory 1.3.2
	- structory_towers 1.0.3
	- suitablystackablestew 1.1.2
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.12+d
	- supplementaries 1.20-2.5.28
	- suppsquared 1.20-1.1.5
	- surfacemushrooms 3.1
	- t_and_t 1.10.2
	- tall-flower-pots 0.1.2
	- techsupportred 1.0.0
	- terrablender 3.0.0.169
	- thepotsmod 1.20.1-Fabric-1.1
	- tidal_towns 1.3
	- tlc 1.0.1
	- toolstats 16.0.3
	- tooltipfix 1.1.1-1.20
	- totw_additions 1.3
	- trashcans 1.0.18
	   \-- team_reborn_energy 3.0.0
	- travelersbackpack 1.20.1-9.1.3
	- traverse 7.0.9
	   |-- biolith 1.0.0-alpha.8
	   |    \-- terraform-surfaces-api-v1 7.0.1
	   |-- terraform-biome-remapper-api-v1 7.0.1
	   |-- terraform-config-api-v1 7.0.1
	   |-- terraform-surfaces-api-v1 7.0.1
	   |-- terraform-tree-api-v1 7.0.1
	   |-- terraform-wood-api-v1 7.0.1
	   |-- traverse-client 7.0.9
	   |-- traverse-common 7.0.9
	   \-- traverse-worldgen 7.0.9
	- trenzalore 3.0.1
	- trinkets 3.7.1
	- tweakeroo 0.17.1
	- twigs 3.1.0
	- universalbonemeal 8.0.1
	- universalenchants 8.0.0
	   |-- cardinal-components-base 5.2.1
	   |-- cardinal-components-entity 5.2.1
	   \-- extensibleenums 7.0.1
	- valhelsia_core 1.1.1
	- valhelsia_furniture 1.1.2
	- vanilla_degus 1.4.0
	- varietyapi 1.0
	- varietyaquatic 1.0.4.8
	- villagernames 5.2
	- villagersplus 2.0
	- vineclipper 1.0.0
	- visualworkbench 8.0.0
	- voidtotem 3.0.1
	   |-- cardinal-components-base 5.2.1
	   \-- cardinal-components-entity 5.2.1
	- wabi_sabi_structures 2.0.0-1.20
	- wafflesmoss v1.0 Fabric 1.20.1
	- waxablecoral unspecified
	- way2wayfabric 0.0.5
	- waystones 14.0.1
	- whydoesmyglasssoundlikethat 1.1.0
	- wi_zoom 1.4-MC1.20.1
	- wilderwild 2.1.3-Fabric+1.20.1
	   |-- frozenlib 1.3.7-Fabric+1.20.1
	   |    \-- blue_endless_jankson 1.2.3
	   \-- nbtcrafting 2.2.3+mc1.20
	- wildlife 1.19.2-2.2
	- woods_and_mires 2.1.1+1.20.1
	   \-- com_typesafe_config 1.4.2
	- woof 4.0.2+1.20.1
	- xaerominimap 23.4.4
	- xaeroworldmap 1.33.1
	- xxlpackets 1.0.4-1.20.x-1.20.1
	- ydms_redpanda 1.0.4
```
</details>
**Expected Behavior**

~~Recipe data is split over multiple packets or something.~~ It seems like this already happens. Perhaps some debug info on exception sending packets could be useful (what it is trying to serialize, etc)

**Screenshots**
![image](https://github.com/FrozenBlock/WilderWild/assets/9504279/ec484d07-0724-49e5-92de-243f64f14b23)

**Logs**

**Additional context**

I'm assuming this has something to do with how NBT crafting generates recipe packets, but I'm not sure how to get debug information out of this: https://github.com/Treetrain1/nbt-crafting/blob/jitpack-1.20/src/main/java/de/siphalor/nbtcrafting/NbtCrafting.java#L201

**Comment by AViewFromTheTop** [comment]
@Treetrain1 this one's definitely for you lol

**Comment by ethanhs** [comment]
Hmm so I did that and I'm not seeing an error print (FWIW I tried modifying things via this commit here: https://github.com/Treetrain1/nbt-crafting/compare/jitpack-1.20...ethanhs:nbt-crafting:jitpack-1.20). I'd expect for *something* to be printed to the server log but I see nothing, which makes me think it is a different packet causing this issue.

**Comment by AViewFromTheTop** [comment]
@ethanhs are you sure the issue may not be caused by another mod you’re using? or does the issue persist just with Wilder Wild alone?

**Comment by ethanhs** [comment]
No I am not sure, the traceback looked a lot like a similar issue caused by nbt-crafting so that was my first suspect, but it seems that may not be the case.

**Comment by ethanhs** [comment]
I have eliminated this mod as the potential cause, sorry for the noise!
