### ISSUE TITLE
fabric 1.20.4 found bug with `net.frozenblock.wilderwild.block.HangingTendrilBlock`

### ISSUE THREAD

**Issue by PixelSymbols** [FrozenBlock/WilderWild#358]
**Description of the Bug Encountered**
i got a bug bcz of wilderwilds block or smth.

**Steps To Reproduce**
1. Install c2me, chunky and wilderwilds
2. run generation of 1024 chunk radius distance
3. sometime later c2me will crash server because of wilder wilds mod

version: fabric 1.20.4
last version of every mod
**Expected Behavior**

should not crash

**Screenshots**
![image](https://github.com/FrozenBlock/WilderWild/assets/81364140/46a550d0-62c5-4a09-ba09-108120508fca)

**Logs**
```
[08:41:23] [c2me-prioritized-2/WARN]: Tried to access a block entity before it was created. class_2338{x=2728, y=4, z=-3849}
[08:41:49] [c2me-prioritized-2/ERROR]: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: c2me-prioritized-2)
This is usually NOT a bug in C2ME, but a bug in another mod or in vanilla code.
Possible solutions:
  - Find possible causes in the stack trace below and
    - if caused by another mod, report this to the corresponding mod authors
    - if no other mods are involved, report this to C2ME

java.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: c2me-prioritized-2)
        at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.handleNotOwner(com/ishland/c2me/fixes/worldgen/threading_issues/common/CheckedThreadLocalRandom.java:55) ~[c2me-fixes-worldgen-threading-isalpha.11.58-3120ea63786edc93.jar:?]
        at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.isSafe(com/ishland/c2me/fixes/worldgen/threading_issues/common/CheckedThreadLocalRandom.java:38) ~[c2me-fixes-worldgen-threading-isalpha.11.58-3120ea63786edc93.jar:?]
        at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.method_43156(com/ishland/c2me/fixes/worldgen/threading_issues/common/CheckedThreadLocalRandom.java:86) ~[c2me-fixes-worldgen-threading-isalpha.11.58-3120ea63786edc93.jar:?]
        at net.minecraft.class_6566.method_43048(class_6566.java:33) ~[server-intermediary.jar:?]
        at net.minecraft.class_1303.method_31496(net/minecraft/class_1303.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_1303.method_31493(net/minecraft/class_1303.java:154) ~[server-intermediary.jar:?]
        at net.minecraft.class_2248.method_9583(net/minecraft/class_2248.java:414) ~[server-intermediary.jar:?]
        at net.minecraft.class_2248.method_41420(net/minecraft/class_2248.java:597) ~[server-intermediary.jar:?]
        at net.frozenblock.wilderwild.block.HangingTendrilBlock.method_9565(HangingTendrilBlock.java:272) ~[WilderWild-2.3.2-Fabric+1.20.4.jar:?]
        at net.minecraft.class_4970$class_4971.method_26180(net/minecraft/class_4970$class_4971.java:1215) ~[server-intermediary.jar:?]
        at net.minecraft.class_2248.method_9511(net/minecraft/class_2248.java:369) ~[server-intermediary.jar:?]
        at net.minecraft.class_3233.method_30093(net/minecraft/class_3233.java:209) ~[server-intermediary.jar:?]
        at net.minecraft.class_1945.method_8651(class_1945.java:27) ~[server-intermediary.jar:?]
        at net.minecraft.class_1945.method_22352(class_1945.java:22) ~[server-intermediary.jar:?]
        at net.frozenblock.wilderwild.block.HangingTendrilBlock.method_9559(HangingTendrilBlock.java:140) ~[WilderWild-2.3.2-Fabric+1.20.4.jar:?]
        at net.minecraft.class_4970$class_4971.method_26191(net/minecraft/class_4970$class_4971.java:1239) ~[server-intermediary.jar:?]
        at net.minecraft.class_2248.method_9510(net/minecraft/class_2248.java:163) ~[server-intermediary.jar:?]
        at net.minecraft.class_3499.method_15172(net/minecraft/class_3499.java:330) ~[server-intermediary.jar:?]
        at com.telepathicgrunt.repurposedstructures.world.features.NbtDungeon.method_13151(NbtDungeon.java:157) ~[repurposed_structures-7.3.2+1.20.4-fabric.jar:?]
        at net.minecraft.class_2975.method_12862(com/ishland/c2me/opts/allocs/mixin/object_pooling_caching/MixinConfiguredFeature.java [c2me-opts-allocs.mixins.json]:37) ~[server-intermediary.jar:?]
        at net.minecraft.class_6796.method_39646(net/minecraft/class_6796.java:54) ~[server-intermediary.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
        at java.util.stream.IntPipeline$1$1.accept(Unknown Source) ~[?:?]
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.Spliterator$OfInt.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
        at net.minecraft.class_6796.method_39648(net/minecraft/class_6796.java:53) ~[server-intermediary.jar:?]
        at net.minecraft.class_6796.method_39650(net/minecraft/class_6796.java:42) ~[server-intermediary.jar:?]
        at net.minecraft.class_2794.method_12102(net/minecraft/class_2794.java:357) ~[server-intermediary.jar:?]
        at net.minecraft.class_2806.method_51375(net/minecraft/class_2806.java:108) ~[server-intermediary.jar:?]
        at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309) ~[server-intermediary.jar:?]
        at net.minecraft.class_2806.md33c974$c2me-threading-worldgen$lambda$runGenerationTask$0$4(com/ishland/c2me/threading/worldgen/mixin/MixinChunkStatus.java [c2me-threading-worldgen.mixins.json]:107) ~[server-intermediary.jar:?]
        at com.ishland.c2me.base.common.scheduler.ScheduledTask.run(ScheduledTask.java:22) ~[c2me-base-0.2.0+alpha.11.58-6e5976acbba24c95.jar:?]
        at com.ishland.flowsched.executor.WorkerThread.pollTasks(WorkerThread.java:56) ~[c2me-base-0.2.0+alpha.11.58-6e5976acbba24c95.jar:?]
        at com.ishland.flowsched.executor.WorkerThread.run(WorkerThread.java:27) ~[c2me-base-0.2.0+alpha.11.58-6e5976acbba24c95.jar:?]
[08:41:49] [c2me-prioritized-2/ERROR]: Negative index in crash report handler (0/7)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]: java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at com.ishland.c2me.base.common.scheduler.ScheduledTask.propagateException(ScheduledTask.java:41)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at com.ishland.flowsched.executor.WorkerThread.pollTasks(WorkerThread.java:71)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at com.ishland.flowsched.executor.WorkerThread.run(WorkerThread.java:27)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]: Caused by: net.minecraft.class_148: Feature placement
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_2794.method_12102(class_2794.java:377)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_2806.method_51375(class_2806.java:108)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_2806.md33c974$c2me-threading-worldgen$lambda$runGenerationTask$0$4(class_2806.java:1607)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at com.ishland.c2me.base.common.scheduler.ScheduledTask.run(ScheduledTask.java:22)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at com.ishland.flowsched.executor.WorkerThread.pollTasks(WorkerThread.java:56)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         ... 1 more
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]: Caused by: com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom$1: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: c2me-prioritized-2)
This is usually NOT a bug in C2ME, but a bug in another mod or in vanilla code.
Possible solutions:
  - Find possible causes in the stack trace below and
    - if caused by another mod, report this to the corresponding mod authors
    - if no other mods are involved, report this to C2ME

 (You may make this a fatal warning instead of a hard crash with fixes.enforceSafeWorldRandomAccess setting in c2me.toml)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]: Caused by: java.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: c2me-prioritized-2)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.handleNotOwner(com/ishland/c2me/fixes/worldgen/threading_issues/common/CheckedThreadLocalRandom.java:55)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.isSafe(com/ishland/c2me/fixes/worldgen/threading_issues/common/CheckedThreadLocalRandom.java:38)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.method_43156(com/ishland/c2me/fixes/worldgen/threading_issues/common/CheckedThreadLocalRandom.java:86)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_6566.method_43048(class_6566.java:33)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_1303.method_31496(net/minecraft/class_1303.java:162)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_1303.method_31493(net/minecraft/class_1303.java:154)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_2248.method_9583(net/minecraft/class_2248.java:414)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_2248.method_41420(net/minecraft/class_2248.java:597)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.frozenblock.wilderwild.block.HangingTendrilBlock.method_9565(HangingTendrilBlock.java:272)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_4970$class_4971.method_26180(net/minecraft/class_4970$class_4971.java:1215)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_2248.method_9511(net/minecraft/class_2248.java:369)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_3233.method_30093(net/minecraft/class_3233.java:209)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_1945.method_8651(class_1945.java:27)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_1945.method_22352(class_1945.java:22)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.frozenblock.wilderwild.block.HangingTendrilBlock.method_9559(HangingTendrilBlock.java:140)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_4970$class_4971.method_26191(net/minecraft/class_4970$class_4971.java:1239)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_2248.method_9510(net/minecraft/class_2248.java:163)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_3499.method_15172(net/minecraft/class_3499.java:330)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at com.telepathicgrunt.repurposedstructures.world.features.NbtDungeon.method_13151(NbtDungeon.java:157)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_2975.method_12862(com/ishland/c2me/opts/allocs/mixin/object_pooling_caching/MixinConfiguredFeature.java [c2me-opts-allocs.mixins.json]:37)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_6796.method_39646(net/minecraft/class_6796.java:54)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.IntPipeline$1$1.accept(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.Spliterator$OfInt.forEachRemaining(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_6796.method_39648(net/minecraft/class_6796.java:53)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_6796.method_39650(net/minecraft/class_6796.java:42)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_2794.method_12102(net/minecraft/class_2794.java:357)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_2806.method_51375(net/minecraft/class_2806.java:108)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at net.minecraft.class_2806.md33c974$c2me-threading-worldgen$lambda$runGenerationTask$0$4(com/ishland/c2me/threading/worldgen/mixin/MixinChunkStatus.java [c2me-threading-worldgen.mixins.json]:107)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at com.ishland.c2me.base.common.scheduler.ScheduledTask.run(ScheduledTask.java:22)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at com.ishland.flowsched.executor.WorkerThread.pollTasks(WorkerThread.java:56)
[08:41:49] [c2me-prioritized-2/INFO]: [STDERR]:         at com.ishland.flowsched.executor.WorkerThread.run(WorkerThread.java:27)
[08:41:49] [minecraft_overworld - Light/ERROR]: Uncaught exception in thread "minecraft_overworld - Light"
java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
        at com.ishland.c2me.base.common.scheduler.ScheduledTask.propagateException(ScheduledTask.java:41) ~[c2me-base-0.2.0+alpha.11.58-6e5976acbba24c95.jar:?]
        at com.ishland.flowsched.executor.WorkerThread.pollTasks(WorkerThread.java:71) ~[c2me-base-0.2.0+alpha.11.58-6e5976acbba24c95.jar:?]
        at com.ishland.flowsched.executor.WorkerThread.run(WorkerThread.java:27) ~[c2me-base-0.2.0+alpha.11.58-6e5976acbba24c95.jar:?]
Caused by: net.minecraft.class_148: Feature placement
        at net.minecraft.class_2794.method_12102(class_2794.java:377) ~[server-intermediary.jar:?]
        at net.minecraft.class_2806.method_51375(class_2806.java:108) ~[server-intermediary.jar:?]
        at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309) ~[server-intermediary.jar:?]
        at net.minecraft.class_2806.md33c974$c2me-threading-worldgen$lambda$runGenerationTask$0$4(class_2806.java:1607) ~[server-intermediary.jar:?]
        at com.ishland.c2me.base.common.scheduler.ScheduledTask.run(ScheduledTask.java:22) ~[c2me-base-0.2.0+alpha.11.58-6e5976acbba24c95.jar:?]
        at com.ishland.flowsched.executor.WorkerThread.pollTasks(WorkerThread.java:56) ~[c2me-base-0.2.0+alpha.11.58-6e5976acbba24c95.jar:?]
        ... 1 more
Caused by: com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom$1: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: c2me-prioritized-2)
This is usually NOT a bug in C2ME, but a bug in another mod or in vanilla code.
Possible solutions:
  - Find possible causes in the stack trace below and
    - if caused by another mod, report this to the corresponding mod authors
    - if no other mods are involved, report this to C2ME

 (You may make this a fatal warning instead of a hard crash with fixes.enforceSafeWorldRandomAccess setting in c2me.toml)
Caused by: java.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: c2me-prioritized-2)
        at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.handleNotOwner(com/ishland/c2me/fixes/worldgen/threading_issues/common/CheckedThreadLocalRandom.java:55) ~[c2me-fixes-worldgen-threading-isalpha.11.58-3120ea63786edc93.jar:?]
        at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.isSafe(com/ishland/c2me/fixes/worldgen/threading_issues/common/CheckedThreadLocalRandom.java:38) ~[c2me-fixes-worldgen-threading-isalpha.11.58-3120ea63786edc93.jar:?]
        at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.method_43156(com/ishland/c2me/fixes/worldgen/threading_issues/common/CheckedThreadLocalRandom.java:86) ~[c2me-fixes-worldgen-threading-isalpha.11.58-3120ea63786edc93.jar:?]
        at net.minecraft.class_6566.method_43048(class_6566.java:33) ~[server-intermediary.jar:?]
        at net.minecraft.class_1303.method_31496(net/minecraft/class_1303.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_1303.method_31493(net/minecraft/class_1303.java:154) ~[server-intermediary.jar:?]
        at net.minecraft.class_2248.method_9583(net/minecraft/class_2248.java:414) ~[server-intermediary.jar:?]
        at net.minecraft.class_2248.method_41420(net/minecraft/class_2248.java:597) ~[server-intermediary.jar:?]
        at net.frozenblock.wilderwild.block.HangingTendrilBlock.method_9565(HangingTendrilBlock.java:272) ~[WilderWild-2.3.2-Fabric+1.20.4.jar:?]
        at net.minecraft.class_4970$class_4971.method_26180(net/minecraft/class_4970$class_4971.java:1215) ~[server-intermediary.jar:?]
        at net.minecraft.class_2248.method_9511(net/minecraft/class_2248.java:369) ~[server-intermediary.jar:?]
        at net.minecraft.class_3233.method_30093(net/minecraft/class_3233.java:209) ~[server-intermediary.jar:?]
        at net.minecraft.class_1945.method_8651(class_1945.java:27) ~[server-intermediary.jar:?]
        at net.minecraft.class_1945.method_22352(class_1945.java:22) ~[server-intermediary.jar:?]
        at net.frozenblock.wilderwild.block.HangingTendrilBlock.method_9559(HangingTendrilBlock.java:140) ~[WilderWild-2.3.2-Fabric+1.20.4.jar:?]
        at net.minecraft.class_4970$class_4971.method_26191(net/minecraft/class_4970$class_4971.java:1239) ~[server-intermediary.jar:?]
        at net.minecraft.class_2248.method_9510(net/minecraft/class_2248.java:163) ~[server-intermediary.jar:?]
        at net.minecraft.class_3499.method_15172(net/minecraft/class_3499.java:330) ~[server-intermediary.jar:?]
        at com.telepathicgrunt.repurposedstructures.world.features.NbtDungeon.method_13151(NbtDungeon.java:157) ~[repurposed_structures-7.3.2+1.20.4-fabric.jar:?]
        at net.minecraft.class_2975.method_12862(com/ishland/c2me/opts/allocs/mixin/object_pooling_caching/MixinConfiguredFeature.java [c2me-opts-allocs.mixins.json]:37) ~[server-intermediary.jar:?]
        at net.minecraft.class_6796.method_39646(net/minecraft/class_6796.java:54) ~[server-intermediary.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
        at java.util.stream.IntPipeline$1$1.accept(Unknown Source) ~[?:?]
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.Spliterator$OfInt.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
        at net.minecraft.class_6796.method_39648(net/minecraft/class_6796.java:53) ~[server-intermediary.jar:?]
        at net.minecraft.class_6796.method_39650(net/minecraft/class_6796.java:42) ~[server-intermediary.jar:?]
        at net.minecraft.class_2794.method_12102(net/minecraft/class_2794.java:357) ~[server-intermediary.jar:?]
        at net.minecraft.class_2806.method_51375(net/minecraft/class_2806.java:108) ~[server-intermediary.jar:?]
        at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309) ~[server-intermediary.jar:?]
        at net.minecraft.class_2806.md33c974$c2me-threading-worldgen$lambda$runGenerationTask$0$4(com/ishland/c2me/threading/worldgen/mixin/MixinChunkStatus.java [c2me-threading-worldgen.mixins.json]:107) ~[server-intermediary.jar:?]
        at com.ishland.c2me.base.common.scheduler.ScheduledTask.run(ScheduledTask.java:22) ~[c2me-base-0.2.0+alpha.11.58-6e5976acbba24c95.jar:?]
        at com.ishland.flowsched.executor.WorkerThread.pollTasks(WorkerThread.java:56) ~[c2me-base-0.2.0+alpha.11.58-6e5976acbba24c95.jar:?]
        ... 1 more
```

**Additional context**
fix please UwU

**Comment by AViewFromTheEnd** [comment]
Despite what the logs say, would you be able to reproduce this without C2ME?

**Comment by PixelSymbols** [comment]
> Despite what the logs say, would you be able to reproduce this without C2ME?

lemmy try

**Comment by AViewFromTheEnd** [comment]
That occurs without C2ME sometimes.
It’s better than the game crashing though!

**Comment by PixelSymbols** [comment]
still, annoying console spam.

**Comment by PixelSymbols** [comment]
> Despite what the logs say, would you be able to reproduce this without C2ME?

yes it works without c2me. I will send this issue to c2me then. Or can you?

**Comment by AViewFromTheTop** [comment]
I'm closing this as it is not only
A) A C2ME issue that will easily impact modders making XP-related features.
But also
B) In Wilder Wild 2.4 I'm going to alter how Hanging Tendrils drop XP so this won't matter anyway.
I still don't appreciate that C2ME won't fix this on their side, but I digress.
One more line in the changelog.
