### ISSUE TITLE
Game crashing after the "Porting to Java 21" commit

### ISSUE THREAD

**Issue by SonicGamerEpisode55** [FrozenBlock/WilderWild#366]
**Description of the Bug Encountered**

**Steps To Reproduce**
1. Build
2. Try to launch the game

**Expected Behavior**
The game runs

**Screenshots**

**Logs**
```
Prism Launcher version: 9.0-develop (unknown)


Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.213.67, 13.107.246.67, 2620:1ec:bdf::67, 2620:1ec:46::67]

textures.minecraft.net resolves to:
    [13.107.246.67, 13.107.213.67, 2620:1ec:bdf::67, 2620:1ec:46::67]

api.mojang.com resolves to:
    [13.107.213.67, 13.107.246.67, 2620:1ec:46::67, 2620:1ec:bdf::67]


Minecraft folder is:
/home/shared/prismlauncher/instances/cats/.minecraft


Java path is:
/usr/lib/jvm/java-21-temurin/bin/java


Java is version 21.0.2, using 64 (amd64) architecture, from Eclipse Adoptium.


AMD Ryzen 3 3200G with Radeon Vega Graphics
Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] (rev c7)

Subsystem: ASRock Incorporation Navi 23 [Radeon RX 6600/6600 XT/6600M]

Kernel driver in use: amdgpu

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  /home/shared/prismlauncher/instances/cats/natives

Traits:
traits feature:is_quick_play_multiplayer
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  /home/shared/prismlauncher/libraries/org/lwjgl/lwjgl-freetype-natives-linux/3.3.2/lwjgl-freetype-natives-linux-3.3.2.jar
  /home/shared/prismlauncher/libraries/org/lwjgl/lwjgl-freetype/3.3.2/lwjgl-freetype-3.3.2.jar
  /home/shared/prismlauncher/libraries/org/lwjgl/lwjgl-glfw-natives-linux/3.3.2/lwjgl-glfw-natives-linux-3.3.2.jar
  /home/shared/prismlauncher/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar
  /home/shared/prismlauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-linux/3.3.2/lwjgl-jemalloc-natives-linux-3.3.2.jar
  /home/shared/prismlauncher/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar
  /home/shared/prismlauncher/libraries/org/lwjgl/lwjgl-natives-linux/3.3.2/lwjgl-natives-linux-3.3.2.jar
  /home/shared/prismlauncher/libraries/org/lwjgl/lwjgl-openal-natives-linux/3.3.2/lwjgl-openal-natives-linux-3.3.2.jar
  /home/shared/prismlauncher/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar
  /home/shared/prismlauncher/libraries/org/lwjgl/lwjgl-opengl-natives-linux/3.3.2/lwjgl-opengl-natives-linux-3.3.2.jar
  /home/shared/prismlauncher/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar
  /home/shared/prismlauncher/libraries/org/lwjgl/lwjgl-stb-natives-linux/3.3.2/lwjgl-stb-natives-linux-3.3.2.jar
  /home/shared/prismlauncher/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar
  /home/shared/prismlauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-linux/3.3.2/lwjgl-tinyfd-natives-linux-3.3.2.jar
  /home/shared/prismlauncher/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar
  /home/shared/prismlauncher/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar
  /home/shared/prismlauncher/libraries/com/github/oshi/oshi-core/6.4.10/oshi-core-6.4.10.jar
  /home/shared/prismlauncher/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  /home/shared/prismlauncher/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/shared/prismlauncher/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  /home/shared/prismlauncher/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  /home/shared/prismlauncher/libraries/com/mojang/authlib/6.0.52/authlib-6.0.52.jar
  /home/shared/prismlauncher/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /home/shared/prismlauncher/libraries/com/mojang/brigadier/1.2.9/brigadier-1.2.9.jar
  /home/shared/prismlauncher/libraries/com/mojang/datafixerupper/7.0.13/datafixerupper-7.0.13.jar
  /home/shared/prismlauncher/libraries/com/mojang/logging/1.2.7/logging-1.2.7.jar
  /home/shared/prismlauncher/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /home/shared/prismlauncher/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  /home/shared/prismlauncher/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  /home/shared/prismlauncher/libraries/commons-io/commons-io/2.15.1/commons-io-2.15.1.jar
  /home/shared/prismlauncher/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/shared/prismlauncher/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  /home/shared/prismlauncher/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  /home/shared/prismlauncher/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  /home/shared/prismlauncher/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  /home/shared/prismlauncher/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  /home/shared/prismlauncher/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  /home/shared/prismlauncher/libraries/io/netty/netty-transport-native-epoll/4.1.97.Final/netty-transport-native-epoll-4.1.97.Final-linux-aarch_64.jar
  /home/shared/prismlauncher/libraries/io/netty/netty-transport-native-epoll/4.1.97.Final/netty-transport-native-epoll-4.1.97.Final-linux-x86_64.jar
  /home/shared/prismlauncher/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  /home/shared/prismlauncher/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  /home/shared/prismlauncher/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  /home/shared/prismlauncher/libraries/net/java/dev/jna/jna-platform/5.14.0/jna-platform-5.14.0.jar
  /home/shared/prismlauncher/libraries/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar
  /home/shared/prismlauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/shared/prismlauncher/libraries/org/apache/commons/commons-compress/1.26.0/commons-compress-1.26.0.jar
  /home/shared/prismlauncher/libraries/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar
  /home/shared/prismlauncher/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/shared/prismlauncher/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  /home/shared/prismlauncher/libraries/org/apache/logging/log4j/log4j-api/2.22.1/log4j-api-2.22.1.jar
  /home/shared/prismlauncher/libraries/org/apache/logging/log4j/log4j-core/2.22.1/log4j-core-2.22.1.jar
  /home/shared/prismlauncher/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.22.1/log4j-slf4j2-impl-2.22.1.jar
  /home/shared/prismlauncher/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  /home/shared/prismlauncher/libraries/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar
  /home/shared/prismlauncher/libraries/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar
  /home/shared/prismlauncher/libraries/net/fabricmc/intermediary/24w14a/intermediary-24w14a.jar
  /home/shared/prismlauncher/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar
  /home/shared/prismlauncher/libraries/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar
  /home/shared/prismlauncher/libraries/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar
  /home/shared/prismlauncher/libraries/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar
  /home/shared/prismlauncher/libraries/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar
  /home/shared/prismlauncher/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar
  /home/shared/prismlauncher/libraries/net/fabricmc/fabric-loader/0.15.9/fabric-loader-0.15.9.jar
  /home/shared/prismlauncher/libraries/com/mojang/minecraft/24w14a/minecraft-24w14a-client.jar

Native libraries:

Mods:
  [✘] c2me-fabric-mc24w13a-0.2.0+alpha.11.77.jar (disabled)
  [✘] cloth-config-14.0.123-fabric.jar (disabled)
  [✘] dynamic-fps-3.4.2+minecraft-1.20.5-alpha.24w09a-fabric.jar (disabled)
  [✘] embeddium-fabric-0.3.9+mc24w13a.jar (disabled)
  [✔] fabric-api-0.96.14+1.20.5
  [✘] fabric-carpet-24w13a-1.4.136+v240327.jar (disabled)
  [✘] modmenu-10.0.0-alpha.3.jar (disabled)
  [✘] RoughlyEnoughItems-14.0.691-alpha-fabric.jar (disabled)
  [✔] StackDeobfuscatorFabric-1.4.2+bf1fc22
  [✘] WilderWild-2.4-Fabric+24w13a.jar (disabled)
  [✔] WilderWild-2.4-Fabric+24w14a
  [✘] zume-0.18.0.jar (disabled)

Params:
  --username  --version 24w14a --gameDir /home/shared/prismlauncher/instances/cats/.minecraft --assetsDir /home/shared/prismlauncher/assets --assetIndex 16 --uuid  --accessToken  --userType  --versionType snapshot

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-Xms512m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 4770


[08:41:44] [main/INFO]: Loading Minecraft 24w14a with Fabric Loader 0.15.9
[08:41:45] [main/INFO]: Loading 58 mods:
	- fabric-api 0.96.14+1.20.5
	   |-- fabric-api-base 0.4.39+80f8cf511f
	   |-- fabric-api-lookup-api-v1 1.6.58+e9d2a72b1f
	   |-- fabric-biome-api-v1 13.0.22+b21c00cb1f
	   |-- fabric-block-api-v1 1.0.19+6dfe4c9b1f
	   |-- fabric-block-view-api-v2 1.0.7+80f8cf511f
	   |-- fabric-blockrenderlayer-v1 1.1.49+80f8cf511f
	   |-- fabric-client-tags-api-v1 1.1.10+80f8cf511f
	   |-- fabric-command-api-v1 1.2.44+f71b366f1f
	   |-- fabric-command-api-v2 2.2.23+80f8cf511f
	   |-- fabric-commands-v0 0.2.61+df3654b31f
	   |-- fabric-content-registries-v0 6.0.16+9b3069f61f
	   |-- fabric-convention-tags-v1 1.5.16+b21c00cb1f
	   |-- fabric-crash-report-info-v1 0.2.26+80f8cf511f
	   |-- fabric-data-attachment-api-v1 1.1.11+97f703da1f
	   |-- fabric-data-generation-api-v1 18.0.2+97f703da1f
	   |-- fabric-dimensions-v1 2.1.66+b21c00cb1f
	   |-- fabric-entity-events-v1 1.6.7+e9d2a72b1f
	   |-- fabric-events-interaction-v0 0.7.5+109a837c1f
	   |-- fabric-events-lifecycle-v0 0.2.86+df3654b31f
	   |-- fabric-game-rule-api-v1 1.0.49+80f8cf511f
	   |-- fabric-item-api-v1 7.0.0+f1e646e41f
	   |-- fabric-item-group-api-v1 4.0.34+42c290b41f
	   |-- fabric-key-binding-api-v1 1.0.44+80f8cf511f
	   |-- fabric-keybindings-v0 0.2.42+df3654b31f
	   |-- fabric-lifecycle-events-v1 2.3.3+9b3069f61f
	   |-- fabric-loot-api-v2 3.0.0+97f703da1f
	   |-- fabric-message-api-v1 6.0.9+109a837c1f
	   |-- fabric-model-loading-api-v1 1.0.11+80f8cf511f
	   |-- fabric-models-v0 0.4.10+9386d8a71f
	   |-- fabric-networking-api-v1 4.0.6+9342ba641f
	   |-- fabric-object-builder-api-v1 15.0.2+97f703da1f
	   |-- fabric-particles-v1 3.0.0+b21c00cb1f
	   |-- fabric-recipe-api-v1 5.0.1+b21c00cb1f
	   |-- fabric-registry-sync-v0 5.0.12+f1e646e41f
	   |-- fabric-renderer-api-v1 3.2.11+97f703da1f
	   |-- fabric-renderer-indigo 1.5.11+80f8cf511f
	   |-- fabric-renderer-registries-v1 3.2.60+df3654b31f
	   |-- fabric-rendering-data-attachment-v1 0.3.45+73761d2e1f
	   |-- fabric-rendering-fluids-v1 3.1.2+2c869ded1f
	   |-- fabric-rendering-v0 1.1.63+df3654b31f
	   |-- fabric-rendering-v1 4.2.3+b21c00cb1f
	   |-- fabric-resource-conditions-api-v1 3.0.1+e9d2a72b1f
	   |-- fabric-resource-loader-v0 1.0.1+e9d2a72b1f
	   |-- fabric-screen-api-v1 2.0.20+7b70ea8a1f
	   |-- fabric-screen-handler-api-v1 1.3.69+b21c00cb1f
	   |-- fabric-sound-api-v1 1.0.20+80f8cf511f
	   |-- fabric-transfer-api-v1 5.1.4+b21c00cb1f
	   \-- fabric-transitive-access-wideners-v1 6.0.8+b21c00cb1f
	- fabricloader 0.15.9
	   \-- mixinextras 0.3.5
	- java 21
	- minecraft 1.20.5-alpha.24.14.a
	- stackdeobfuscator 1.4.2+bf1fc22
	   |-- dev_booky_common_ 1.4.2+bf1fc22
	   \-- net_fabricmc_mapping-io 0.3.0
	- wilderwild 2.4-Fabric+24w14a
	   \-- frozenlib 1.6.3-Fabric+24w14a
[08:41:45] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/shared/prismlauncher/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[08:41:45] [main/INFO]: Compatibility level set to JAVA_17
[08:41:45] [main/WARN]: The requested compatibility level JAVA_18 is higher than the level supported by the active subsystem 'Knot/Fabric' which supports JAVA_17. This is not a supported configuration and instability may occur.
[08:41:45] [main/INFO]: Compatibility level set to JAVA_18
[08:41:46] [main/INFO]: Loading config MixinsConfig from wilderwild
[08:41:46] [main/INFO]: Saving config MixinsConfig from wilderwild
[08:41:46] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[08:41:47] [main/WARN]: Failed to get system info for GL Caps
java.lang.IllegalStateException: Rendersystem called from wrong thread
	at com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:183) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThread(RenderSystem.java:172) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.getCapsString(RenderSystem.java:872) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37123(class_6396.java:66) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_37274(class_310.java:2599) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_22681(class_310.java:2570) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:178) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-04-07 08:41:47
Description: Bootstrap

java.lang.NoSuchMethodError: 'void net.minecraft.class_6880$class_6883.bindValue(java.lang.Object)'
	at net.minecraft.class_2370.modifyExpressionValue$bac000$frozenlib$quilt$eagerFillReference(class_2370.java:1577)
	at net.minecraft.class_2370.method_10272(class_2370.java:148)
	at net.minecraft.class_7923.method_47478(class_7923.java:234)
	at net.minecraft.class_7923.method_47481(class_7923.java:221)
	at net.minecraft.class_7923.<clinit>(class_7923.java:135)
	at net.minecraft.class_2966.method_12851(class_2966.java:50)
	at net.minecraft.client.main.Main.main(Main.java:170)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraft.class_2370.modifyExpressionValue$bac000$frozenlib$quilt$eagerFillReference(class_2370.java:1577)
	at net.minecraft.class_2370.method_10272(class_2370.java:148)
	at net.minecraft.class_7923.method_47478(class_7923.java:234)
	at net.minecraft.class_7923.method_47481(class_7923.java:221)
	at net.minecraft.class_7923.<clinit>(class_7923.java:135)
	at net.minecraft.class_2966.method_12851(class_2966.java:50)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:170)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
	Minecraft Version: 24w14a
	Minecraft Version ID: 24w14a
	Operating System: Linux (amd64) version 6.8.2-zen2-1-zen
	Java Version: 21.0.2, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 322928776 bytes (307 MiB) / 536870912 bytes (512 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 3 3200G with Radeon Vega Graphics
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Navi 23 [Radeon RX 6600/6600 XT/6600M]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 8448.00
	Graphics card #0 deviceId: 0x73ff
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 16071.27
	Virtual memory used (MB): 8931.40
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Fabric Mods: 
		fabric-api: Fabric API 0.96.14+1.20.5
			fabric-api-base: Fabric API Base 0.4.39+80f8cf511f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.58+e9d2a72b1f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.22+b21c00cb1f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.19+6dfe4c9b1f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.7+80f8cf511f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.49+80f8cf511f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.10+80f8cf511f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.44+f71b366f1f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.23+80f8cf511f
			fabric-commands-v0: Fabric Commands (v0) 0.2.61+df3654b31f
			fabric-content-registries-v0: Fabric Content Registries (v0) 6.0.16+9b3069f61f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.16+b21c00cb1f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.26+80f8cf511f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.11+97f703da1f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 18.0.2+97f703da1f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.66+b21c00cb1f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.7+e9d2a72b1f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.5+109a837c1f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.86+df3654b31f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.49+80f8cf511f
			fabric-item-api-v1: Fabric Item API (v1) 7.0.0+f1e646e41f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.34+42c290b41f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.44+80f8cf511f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.42+df3654b31f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.3+9b3069f61f
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.0+97f703da1f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.9+109a837c1f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.11+80f8cf511f
			fabric-models-v0: Fabric Models (v0) 0.4.10+9386d8a71f
			fabric-networking-api-v1: Fabric Networking API (v1) 4.0.6+9342ba641f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.0.2+97f703da1f
			fabric-particles-v1: Fabric Particles (v1) 3.0.0+b21c00cb1f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.1+b21c00cb1f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.12+f1e646e41f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.11+97f703da1f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.11+80f8cf511f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.60+df3654b31f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.45+73761d2e1f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.2+2c869ded1f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.63+df3654b31f
			fabric-rendering-v1: Fabric Rendering (v1) 4.2.3+b21c00cb1f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 3.0.1+e9d2a72b1f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.0.1+e9d2a72b1f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.20+7b70ea8a1f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.69+b21c00cb1f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.20+80f8cf511f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.4+b21c00cb1f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.8+b21c00cb1f
		fabricloader: Fabric Loader 0.15.9
			mixinextras: MixinExtras 0.3.5
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.20.5-alpha.24.14.a
		stackdeobfuscator: StackDeobfuscator 1.4.2+bf1fc22
			dev_booky_common_: common 1.4.2+bf1fc22
			net_fabricmc_mapping-io: mapping-io 0.3.0
		wilderwild: Wilder Wild 2.4-Fabric+24w14a
			frozenlib: FrozenLib 1.6.3-Fabric+24w14a
	Launched Version: 24w14a
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: ERR
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /home/shared/prismlauncher/instances/cats/.minecraft/crash-reports/crash-2024-04-07_08.41.47-client.txt
Process exited with code 255.
```

**Additional context**

**Comment by Treetrain1** [comment]
Please don't use bleeding edge versions of the mod.

**Comment by AViewFromTheTop** [comment]
> Please don't use bleeding edge versions of the mod.

It’s that loom issue I keep having. We just have to stick with local loom 1.5, I have no idea why newer looms just refuse to work.

**Comment by SonicGamerEpisode55** [comment]
Ok, so I will use the last 24w13a commit of the mod.
