### ISSUE TITLE
Incompatibility with Tectonic on Fabric 1.20.1

### ISSUE THREAD

**Issue by EliConstructor** [FrozenBlock/WilderWild#371]
**Description of the Bug Encountered**
When I try to open an existing world with only Fabric API, Wilder Wild and Tectonic installed, the game fails to load the world, with the message "Failed to access world [world name]" (See screenshot). This doesn't happen with just Tectonic or just Wilder Wild, only both together. It's probably worth noting that generating the world works fine, I can make a new world and the game runs normally. But if I close the world and attempt to reopen it the error will show up.

**Steps To Reproduce**
1. Install the latest versions of Fabric Loader, Fabric API, Tectonic and Wilder Wild on Minecraft 1.20.1
2. Create a world
3. Close the world
4. Attempt to open the same world again

**Expected Behavior**
The world opens as normal

**Screenshots**
![Screenshot 2024-05-02 193419](https://github.com/FrozenBlock/WilderWild/assets/32846069/ed721ab1-cee1-4d65-8462-b983d503307b)
(The world is called test)

**Logs**
Error that shows up in log when attempting to load the world:
```
[19:34:09] [Render thread/WARN]: Failed to read level test data
java.io.IOException: The process cannot access the file because another process has locked a portion of the file
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
	at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:68) ~[?:?]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132) ~[?:?]
	at sun.nio.ch.IOUtil.write(IOUtil.java:76) ~[?:?]
	at sun.nio.ch.IOUtil.write(IOUtil.java:67) ~[?:?]
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:288) ~[?:?]
	at net.minecraft.class_5125.method_26803(class_5125.java:37) ~[client-intermediary.jar:?]
	at net.minecraft.class_32$class_5143.<init>(class_32.java:398) ~[client-intermediary.jar:?]
	at net.minecraft.class_32.method_52236(class_32.java:377) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41901(class_7196.java:101) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41899(class_7196.java:193) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41897(class_7196.java:220) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.handler$zlp000$frozenlib$frozenLib$preventBackupScreenAndProceed(class_7196.java:542) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41898(class_7196.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41899(class_7196.java:220) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41894(class_7196.java:64) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:590) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:480) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:407) ~[client-intermediary.jar:?]
	at net.minecraft.class_350.method_25402(class_350.java:327) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1244) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.10.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
```

**Additional context**
Minecraft version: 1.20.1
Fabric Loader version: 0.15.10
Fabric API version: 0.92.1
Tectonic version: 2.3.4
Wilder Wild version: 2.3.3

**Comment by AViewFromTheTop** [comment]
https://github.com/FrozenBlock/WilderWild/issues/364

**Comment by EliConstructor** [comment]
Could have sworn I searched with those exact words, but I guess I didn't. Disabling removeExperimentalWarning in frozenlib.json5 did the trick, thanks.

**Comment by AViewFromTheTop** [comment]
No problem!
The option’s being set to disabled by default in the next release, so I’m hoping people won’t run into this anymore.
