### ISSUE TITLE
Update 2.4 conflicts with Create latest version patch "f"

### ISSUE THREAD

**Issue by MatiCugno69** [FrozenBlock/WilderWild#373]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-05-04 21:04:30
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'create'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class com.simibubi.create.foundation.placement.IPlacementHelper
		at com.railwayteam.railways.content.semaphore.SemaphoreBlock.<clinit>(SemaphoreBlock.java:42)
		at com.tterrag.registrate.builders.BlockBuilder.createEntry(BlockBuilder.java:333)
		at com.tterrag.registrate.builders.BlockBuilder.createEntry(BlockBuilder.java:44)
		at com.tterrag.registrate.fabric.Lazy.get(Lazy.java:17)
		at com.tterrag.registrate.AbstractRegistrate$Registration.register(AbstractRegistrate.java:121)
		at com.tterrag.registrate.AbstractRegistrate.onRegister(AbstractRegistrate.java:217)
		at com.tterrag.registrate.AbstractRegistrate.lambda$register$1(AbstractRegistrate.java:189)
		at com.tterrag.registrate.fabric.RegistryUtil.forAllRegistries(RegistryUtil.java:12)
		at com.tterrag.registrate.AbstractRegistrate.register(AbstractRegistrate.java:188)
		at com.railwayteam.railways.fabric.RailwaysImpl.finalizeRegistrate(RailwaysImpl.java:44)
		at com.railwayteam.railways.Railways.finalizeRegistrate(Railways.java)
		at com.railwayteam.railways.Railways.init(Railways.java:81)
		at com.railwayteam.railways.fabric.RailwaysImpl.onInitialize(RailwaysImpl.java:25)
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
		... 6 more
	Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Render thread"]
		at net.minecraft.class_2688.method_28498(class_2688.java:92)
		at net.frozenblock.wilderwild.block.impl.SnowloggingUtils.supportsSnowlogging(SnowloggingUtils.java:46)
		at net.frozenblock.wilderwild.block.impl.SnowloggingUtils.isSnowlogged(SnowloggingUtils.java:58)
		at net.minecraft.class_4970$class_4971.wrapOperation$mnj000$wilderwild$wilderWild$useShapeForLightOcclusion(class_4970.java:7551)
		at net.minecraft.class_4970$class_4971.<init>(class_4970.java:790)
		at net.minecraft.class_2680.<init>(class_2680.java:17)
		at com.simibubi.create.foundation.placement.IPlacementHelper.<clinit>(IPlacementHelper.java:35)
		at com.simibubi.create.content.kinetics.simpleRelays.ShaftBlock.<clinit>(ShaftBlock.java:36)
		at com.tterrag.registrate.builders.BlockBuilder.createEntry(BlockBuilder.java:333)
		at com.tterrag.registrate.builders.BlockBuilder.createEntry(BlockBuilder.java:44)
		at com.tterrag.registrate.fabric.Lazy.get(Lazy.java:17)
		at com.tterrag.registrate.AbstractRegistrate$Registration.register(AbstractRegistrate.java:121)
		at com.tterrag.registrate.AbstractRegistrate.onRegister(AbstractRegistrate.java:217)
		at com.tterrag.registrate.AbstractRegistrate.lambda$register$1(AbstractRegistrate.java:189)
		at com.tterrag.registrate.fabric.RegistryUtil.forAllRegistries(RegistryUtil.java:12)
		at com.tterrag.registrate.AbstractRegistrate.register(AbstractRegistrate.java:188)
		at com.simibubi.create.Create.onInitialize(Create.java:115)
		... 7 more
Caused by: java.lang.ExceptionInInitializerError
	at com.simibubi.create.content.kinetics.simpleRelays.ShaftBlock.<clinit>(ShaftBlock.java:36)
	at com.tterrag.registrate.builders.BlockBuilder.createEntry(BlockBuilder.java:333)
	at com.tterrag.registrate.builders.BlockBuilder.createEntry(BlockBuilder.java:44)
	at com.tterrag.registrate.fabric.Lazy.get(Lazy.java:17)
	at com.tterrag.registrate.AbstractRegistrate$Registration.register(AbstractRegistrate.java:121)
	at com.tterrag.registrate.AbstractRegistrate.onRegister(AbstractRegistrate.java:217)
	at com.tterrag.registrate.AbstractRegistrate.lambda$register$1(AbstractRegistrate.java:189)
	at com.tterrag.registrate.fabric.RegistryUtil.forAllRegistries(RegistryUtil.java:12)
	at com.tterrag.registrate.AbstractRegistrate.register(AbstractRegistrate.java:188)
	at com.simibubi.create.Create.onInitialize(Create.java:115)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
Caused by: java.lang.NullPointerException: Cannot invoke "com.google.common.collect.ImmutableMap.containsKey(Object)" because "this.field_24738" is null
	at net.minecraft.class_2688.method_28498(class_2688.java:92)
	at net.frozenblock.wilderwild.block.impl.SnowloggingUtils.supportsSnowlogging(SnowloggingUtils.java:46)
	at net.frozenblock.wilderwild.block.impl.SnowloggingUtils.isSnowlogged(SnowloggingUtils.java:58)
	at net.minecraft.class_4970$class_4971.wrapOperation$mnj000$wilderwild$wilderWild$useShapeForLightOcclusion(class_4970.java:7551)
	at net.minecraft.class_4970$class_4971.<init>(class_4970.java:790)
	at net.minecraft.class_2680.<init>(class_2680.java:17)
	at com.simibubi.create.foundation.placement.IPlacementHelper.<clinit>(IPlacementHelper.java:35)
	... 17 more

**Comment by Treetrain1** [comment]
Already fixed in future update
