### ISSUE TITLE
World file locked when re-entering

### ISSUE THREAD

**Issue by zkll505** [FrozenBlock/WilderWild#384]
**Description of the Bug Encountered**
Minecraft world locked by Wilderwilds

**Steps To Reproduce**
1. create a world
2. exit the world
3. attempt to re-open the world.

**Expected Behavior**
Inability to access world permanently, even after disabling wilderwilds and frozenlib.

**Screenshots**
![image](https://github.com/FrozenBlock/WilderWild/assets/84483653/b07066e6-a571-4f29-b39f-354eeaaf95d9)

**Logs**
Here are the log sections containing the issue.

`[20:33:49] [main/INFO]: Loading config MixinsConfig from wilderwild
[20:33:49] [main/INFO]: Saving config MixinsConfig from wilderwild
[20:33:49] [main/WARN]: Error loading class: net/minecraft/world/World (java.lang.ClassNotFoundException: net/minecraft/world/World)
[20:33:49] [main/WARN]: Error loading class: net/minecraft/world/World (java.lang.ClassNotFoundException: net/minecraft/world/World)
[20:33:49] [main/WARN]: Error loading class: net/minecraft/src/C_4977_ (java.lang.ClassNotFoundException: net/minecraft/src/C_4977_)
[20:33:49] [main/WARN]: Error loading class: net/minecraft/src/C_4977_ (java.lang.ClassNotFoundException: net/minecraft/src/C_4977_)
[20:33:49] [main/WARN]: Error loading class: net/minecraft/server/level/ServerLevel (java.lang.ClassNotFoundException: net/minecraft/server/level/ServerLevel)
[20:33:49] [main/WARN]: Error loading class: net/minecraft/server/world/ServerWorld (java.lang.ClassNotFoundException: net/minecraft/server/world/ServerWorld)
[20:33:49] [main/WARN]: Error loading class: net/minecraft/world/server/ServerWorld (java.lang.ClassNotFoundException: net/minecraft/world/server/ServerWorld)
[20:33:49] [main/WARN]: Error loading class: net/minecraft/src/C_12_ (java.lang.ClassNotFoundException: net/minecraft/src/C_12_)
[20:33:49] [main/WARN]: Error loading class: net/minecraft/unmapped/C_bdwnwhiu (java.lang.ClassNotFoundException: net/minecraft/unmapped/C_bdwnwhiu)
[20:33:49] [main/WARN]: Error loading class: net/minecraft/server/level/ServerLevel (java.lang.ClassNotFoundException: net/minecraft/server/level/ServerLevel)
[20:33:49] [main/WARN]: Error loading class: net/minecraft/server/world/ServerWorld (java.lang.ClassNotFoundException: net/minecraft/server/world/ServerWorld)
[20:33:49] [main/WARN]: Error loading class: net/minecraft/world/server/ServerWorld (java.lang.ClassNotFoundException: net/minecraft/world/server/ServerWorld)
[20:33:49] [main/WARN]: Error loading class: net/minecraft/src/C_12_ (java.lang.ClassNotFoundException: net/minecraft/src/C_12_)
[20:33:49] [main/WARN]: Error loading class: net/minecraft/unmapped/C_bdwnwhiu (java.lang.ClassNotFoundException: net/minecraft/unmapped/C_bdwnwhiu)
[20:33:49] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)
[20:33:49] [main/INFO]: Searching for graphics cards...
[20:33:49] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[20:33:50] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=UNKNOWN, name=USB Mobile Monitor Virtual Display, version=DriverVersion=2.0.0.1]
[20:33:50] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=NVIDIA, name=NVIDIA GeForce GTX 1660 SUPER, version=DriverVersion=31.0.15.5244]
[20:33:50] [main/WARN]: Sodium has applied one or more workarounds to prevent crashes or other issues on your system: [NVIDIA_THREADED_OPTIMIZATIONS]
[20:33:50] [main/WARN]: This is not necessarily an issue, but it may result in certain features or optimizations being disabled. You can sometimes fix these issues by upgrading your graphics driver.
[20:33:52] [main/WARN]: Method overwrite conflict for getInventory in bettercombat.mixins.json:PlayerEntityAccessor from mod bettercombat, previously written by dev.tr7zw.firstperson.mixins.PlayerMixin. Skipping method.
[20:33:52] [main/WARN]: Error loading class: net/minecraft/server/level/ServerLevel (java.lang.ClassNotFoundException: net/minecraft/server/level/ServerLevel)
[20:33:52] [main/WARN]: Error loading class: net/minecraft/server/world/ServerWorld (java.lang.ClassNotFoundException: net/minecraft/server/world/ServerWorld)
[20:33:52] [main/WARN]: Error loading class: net/minecraft/world/server/ServerWorld (java.lang.ClassNotFoundException: net/minecraft/world/server/ServerWorld)
[20:33:52] [main/WARN]: Error loading class: net/minecraft/src/C_12_ (java.lang.ClassNotFoundException: net/minecraft/src/C_12_)
[20:33:52] [main/WARN]: Error loading class: net/minecraft/unmapped/C_bdwnwhiu (java.lang.ClassNotFoundException: net/minecraft/unmapped/C_bdwnwhiu)
[20:33:54] [main/INFO]: Loading config BlockConfig from wilderwild
[20:33:54] [main/INFO]: Saving config BlockConfig from wilderwild
[20:33:55] [main/INFO]: Loading config EntityConfig from wilderwild
[20:33:55] [main/INFO]: Saving config EntityConfig from wilderwild
[20:33:57] [main/WARN]: @ModifyConstant conflict. Skipping yungsapi_fabric.mixins.json:IncreaseStructureWeightLimitMixinFabric from mod yungsapi->@ModifyConstant::yungsapi_increaseWeightLimitProd(I)I with priority 1000, already redirected by dungeonnowloading.fabric.mixins.json:fabric.structures.StructurePoolMixin from mod dungeonnowloading->@ModifyConstant::dungeonnowloading_increaseWeightLimit(I)I with priority 1000
[20:33:57] [main/WARN]: Static binding violation: PRIVATE @Overwrite method method_21740 in modernfix-common.mixins.json:perf.remove_biome_temperature_cache.BiomeMixin from mod modernfix cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.`

`[20:35:30] [Render thread/WARN]: Failed to read level New WorldKKKKKKK data
java.io.IOException: The process cannot access the file because another process has locked a portion of the file
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
	at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:68) ~[?:?]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132) ~[?:?]
	at sun.nio.ch.IOUtil.write(IOUtil.java:76) ~[?:?]
	at sun.nio.ch.IOUtil.write(IOUtil.java:67) ~[?:?]
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:288) ~[?:?]
	at net.minecraft.class_5125.method_26803(class_5125.java:37) ~[client-intermediary.jar:?]
	at net.minecraft.class_32$class_5143.<init>(class_32.java:398) ~[client-intermediary.jar:?]
	at net.minecraft.class_32.method_52236(class_32.java:377) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41901(class_7196.java:101) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41899(class_7196.java:193) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41897(class_7196.java:220) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.handler$ced000$frozenlib$frozenLib$preventBackupScreenAndProceed(class_7196.java:542) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41898(class_7196.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41899(class_7196.java:220) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41894(class_7196.java:64) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:590) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:480) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:402) ~[client-intermediary.jar:?]
	at net.minecraft.class_350.method_25402(class_350.java:327) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1244) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]`

**Additional context**
From experience, probably a compatibility issue, but unsure, as I've been testing, and have gone through every other world-effecting mod, performance mod, and rendering mod, disabling as I go. Unknown as to the cause. Regardless, not being able to access the world again is a big issue.

`Mods:
  [✔️] AmbientSounds_FABRIC_v5.3.9_mc1.20.1.jar
  [✔️] appleskin-fabric-mc1.20.1-2.5.1.jar
  [✔️] architectury-9.2.14-fabric.jar
  [✔️] BadOptimizations-2.1.0.jar
  [✔️] balm-fabric-1.20.1-7.2.2.jar
  [✔️] betterarcheology-1.1.6-1.20.1.jar
  [✔️] bettercombat-fabric-1.8.4+1.20.1.jar
  [✔️] BetterF3-7.0.2-Fabric-1.20.1.jar
  [✔️] blur-3.1.0.jar
  [✔️] bushierflowers-0.0.3-1.20.1.jar
  [✔️] CameraOverhaul-1.4.0-fabric-universal.jar
  [✔️] cave_dust-1.4.1.jar
  [✔️] charmonium-fabric-1.20.1-6.0.7.jar
  [✔️] chunksfadein-v1.0.5-1.20.1.jar
  [✔️] cloth-config-11.1.118-fabric.jar
  [✔️] combatroll-fabric-1.3.1+1.20.1.jar
  [✔️] completeconfig-2.1.0.jar
  [✔️] coroutil-fabric-1.20.1-1.3.7.jar
  [✔️] CreativeCore_FABRIC_v2.11.24_mc1.20.1.jar
  [✔️] Dungeon Now Loading-fabric-1.20.1-1.5.jar
  [✔️] dungeons-and-taverns-3.0.3.jar
  [✔️] DungeonsAriseSevenSeas-1.20.x-1.0.2-fabric.jar
  [✔️] EasyAnvils-v8.0.2-1.20.1-Fabric.jar
  [✔️] EasyMagic-v8.0.1-1.20.1-Fabric.jar
  [✔️] EasyShulkerBoxes-v8.0.2-1.20.1-Fabric.jar
  [✔️] entity_model_features_fabric_1.20.1-1.3.jar
  [✔️] entity_texture_features_fabric_1.20.1-5.2.3.jar
  [✔️] eugenes-wealthy-plains-village-1.0.jar
  [✔️] explosive-enhancement-1.2.2-1.20.x.jar
  [✔️] extraorigins-1.20-1.jar
  [✔️] fabric-api-0.92.2+1.20.1.jar
  [✔️] fabric-language-kotlin-1.10.19+kotlin.1.9.23.jar
  [✔️] firstperson-fabric-2.3.4-mc1.20.1.jar
  [✔️] ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
  [✔️] FrozenLib-1.7.2-Fabric+1.20.1.jar
  [✔️] fusion-1.1.1-fabric-mc1.20.1.jar
  [✔️] gravestones-v1.15.jar
  [✔️] ImmediatelyFast-Fabric-1.2.10+1.20.4.jar
  [✔️] immersive_weathering-1.20.1-2.0.1-fabric.jar
  [✔️] indium-1.0.30+mc1.20.4.jar
  [✔️] iris-mc1.20.1-1.6.17.jar
  [✔️] itemblacklist-0.2.0-mc1.20.jar
  [✔️] jei-1.20.1-fabric-15.3.0.4.jar
  [✔️] Ksyxis-1.2.2.jar
  [✔️] medieval_buildings_fabric-1.0.2.jar
  [✔️] mes-1.3-1.20-fabric.jar
  [✔️] modernfix-fabric-5.14.0+mc1.20.1.jar
  [✔️] modmenu-7.2.2.jar
  [✔️] moonlight-1.20-2.11.4-fabric.jar
  [✔️] more_spawners-1.1.0.jar
  [✔️] MouseTweaks-fabric-mc1.20-2.25.jar
  [✔️] notenoughanimations-fabric-1.7.1-mc1.20.1.jar
  [✔️] Nullscape_1.20.1_v1.2.2.jar
  [✔️] Origins-1.20.1-1.10.0.jar
  [✔️] Pehkui-3.7.12+1.14.4-1.20.4.jar
  [✔️] PickUpNotifier-v8.0.0-1.20.1-Fabric.jar
  [✔️] player-animation-lib-fabric-1.0.2-rc1+1.20.jar
  [✔️] PuzzlesLib-v8.1.17-1.20.1-Fabric.jar
  [✔️] saturn-mc1.19.2-0.1.2.jar
  [✔️] ShoulderSurfing-Fabric-1.20.1-2.9.4.jar
  [✔️] simplyswords-fabric-1.54.0-1.20.1.jar
  [✔️] skinlayers3d-fabric-1.6.2-mc1.20.1.jar
  [✔️] sodium-fabric-0.5.8+mc1.20.1.jar
  [✔️] soundphysics-fabric-1.20.1-1.1.2.jar
  [✔️] statuseffecttimer-1.2.0+1.20.jar
  [✔️] text-utilities-fabric-1.6.1+1.20.1.jar
  [✔️] tia-1.20-1.1-fabric.jar
  [✔️] towers-1.0.1.jar
  [✔️] traverse-7.0.11.jar
  [✔️] voicechat-fabric-1.20.1-2.5.8.jar
  [✔️] watut-fabric-1.20.1-1.1.0.jar
  [✔️] waystones-fabric-1.20-14.1.3.jar
  [✔️] WilderWild-2.4.2-Fabric+1.20.1.jar
  [✔️] Xaeros_Minimap_24.1.1_Fabric_1.20.jar
  [✔️] XaerosWorldMap_1.38.4_Fabric_1.20.jar
  [✔️] yet-another-config-lib-fabric-3.2.2+1.20.jar
  [✔️] YungsApi-1.20-Fabric-4.0.4.jar
  [✔️] Zoomify-2.11.2.jar`

**Comment by AViewFromTheTop** [comment]
what

**Comment by AViewFromTheTop** [comment]
Have you tried opening FrozenLib's config and disabling the option that relates to experimental settings in there?
You'll need Mod Menu and Cloth Config to access it. Just make sure Mod Menu has "Show Libraries" enabled in its settings.

**Comment by zkll505** [comment]
![image](https://github.com/FrozenBlock/WilderWild/assets/84483653/4c04a051-a8b4-4b22-ac37-680b0d1d9626)
![image](https://github.com/FrozenBlock/WilderWild/assets/84483653/10b28488-73ca-465a-8600-0c689a5e2290)
![image](https://github.com/FrozenBlock/WilderWild/assets/84483653/75938382-5949-4f63-aa90-de20ffab9ebf)

Why does this _work???_

Much appreciated response, never seen a Dev respond so quickly with a correct answer! Thanks a million, I was really hoping I wouldn't have to remove _WilderWild_ since it's an epic mod.

I'm not sure how exactly the experimental _warning_ setting is the issue, but thanks!
I'm also curious how having this setting disabled by default would affect the mod since the setting description is only about the experimental warning, not any experimental features.

![image](https://github.com/FrozenBlock/WilderWild/assets/84483653/f8fc1eb0-9255-4247-a775-d16fdf551b34)

Cheers!

**Comment by AViewFromTheTop** [comment]
> Why does this _work???_

It's very weird, but it's clearly a mod compat issue.
Some dev must've hooked into the world loading sequence and required the Experiemtal screen to show up, I'd assume.
If not, I have no clue. It should be disabled by default as of a while ago, but of course I can't exactly erase already existing configs to get that effect.
In any case, I'm very glad it's worked for you! It's much better than having an untraceable issue on our hands.
