### ISSUE TITLE
Crash when starting server with versions above 2.4.9

### ISSUE THREAD

**Issue by MrSzalonna** [FrozenBlock/WilderWild#407]
**Description of the Bug Encountered**
The server is unable to start with the versions above 2.4.9

**Steps To Reproduce**
1. Download the server from the fabric website and accept the EULA,
2. Portforward your router
3. Install the latest version of Wilder wild and Fabric API,
4. Start the server and experience the crash

**Expected Behavior**
Crashes on startup

**Screenshots**

**Logs**
[13:07:16] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.2
[13:07:16] [main/INFO]: Loading 43 mods:
	- fabric-api 0.102.1+1.21.1
	   |-- fabric-api-base 0.4.42+6573ed8c6a
	   |-- fabric-api-lookup-api-v1 1.6.68+b55973446a
	   |-- fabric-biome-api-v1 13.0.29+5bd9f1bc6a
	   |-- fabric-block-api-v1 1.0.22+0af3f5a76a
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8c6a
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a76a
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8c6a
	   |-- fabric-command-api-v1 1.2.49+f71b366f6a
	   |-- fabric-command-api-v2 2.2.28+6ced4dd96a
	   |-- fabric-commands-v0 0.2.66+df3654b36a
	   |-- fabric-content-registries-v0 8.0.16+b55973446a
	   |-- fabric-convention-tags-v1 2.0.20+7f945d5b6a
	   |-- fabric-convention-tags-v2 2.6.0+605f22ad6a
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a76a
	   |-- fabric-data-attachment-api-v1 1.1.27+1daea2156a
	   |-- fabric-data-generation-api-v1 20.2.17+16c4ae256a
	   |-- fabric-dimensions-v1 4.0.0+6fc22b996a
	   |-- fabric-entity-events-v1 1.6.12+6fc22b996a
	   |-- fabric-events-interaction-v0 0.7.12+ba9dae066a
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd96a
	   |-- fabric-item-api-v1 11.0.0+afdfc9216a
	   |-- fabric-item-group-api-v1 4.1.4+780172706a
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a76a
	   |-- fabric-keybindings-v0 0.2.45+df3654b36a
	   |-- fabric-lifecycle-events-v1 2.3.12+6c1df3606a
	   |-- fabric-loot-api-v2 3.0.14+3f89f5a56a
	   |-- fabric-loot-api-v3 1.0.2+3f89f5a56a
	   |-- fabric-message-api-v1 6.0.13+6573ed8c6a
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6b6a
	   |-- fabric-networking-api-v1 4.2.2+60c3209b6a
	   |-- fabric-object-builder-api-v1 15.2.0+40875a936a
	   |-- fabric-particles-v1 4.0.2+6573ed8c6a
	   |-- fabric-recipe-api-v1 5.0.12+650897126a
	   |-- fabric-registry-sync-v0 5.1.2+60c3209b6a
	   |-- fabric-renderer-api-v1 3.4.0+c705a49c6a
	   |-- fabric-renderer-indigo 1.7.0+c705a49c6a
	   |-- fabric-renderer-registries-v1 3.2.68+df3654b36a
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e6a
	   |-- fabric-rendering-fluids-v1 3.1.6+1daea2156a
	   |-- fabric-rendering-v0 1.1.71+df3654b36a
	   |-- fabric-rendering-v1 5.0.5+df16efd06a
	   |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b16a
	   |-- fabric-resource-loader-v0 1.3.0+565991296a
	   |-- fabric-screen-api-v1 2.0.25+8b68f1c76a
	   |-- fabric-screen-handler-api-v1 1.3.86+b55973446a
	   |-- fabric-sound-api-v1 1.0.23+6573ed8c6a
	   |-- fabric-transfer-api-v1 5.1.17+1db1cc1f6a
	   \-- fabric-transitive-access-wideners-v1 6.1.0+1daea2156a
	- fabricloader 0.16.2
	   \-- mixinextras 0.4.1
	- java 22
	- minecraft 1.21.1
	- wilderwild 2.4.10-mc1.21.1
	   \-- frozenlib 1.8.3-mc1.21.1
[13:07:16] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/C:/Users/*MyUserName*EditedByMeBecauseOfPrivacyForThisReport/Downloads/1.21.1%20baby/libraries/net/fabricmc/sponge-mixin/0.15.2+mixin.0.8.7/sponge-mixin-0.15.2+mixin.0.8.7.jar Service=Knot/Fabric Env=SERVER
[13:07:16] [main/INFO]: Compatibility level set to JAVA_17
[13:07:16] [main/INFO]: Compatibility level set to JAVA_21
[13:07:17] [main/INFO]: Loading config MixinsConfig from wilderwild
[13:07:17] [main/INFO]: Saving config MixinsConfig from wilderwild
[13:07:17] [main/ERROR]: Mixin prepare for mod wilderwild failed preparing client.indium.BlockRendererMixin in wilderwild.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Cannot load class net.frozenblock.wilderwild.mixin.client.indium.BlockRendererMixin in environment type SERVER
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Cannot load class net.frozenblock.wilderwild.mixin.client.indium.BlockRendererMixin in environment type SERVER
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:864) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:933) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:858) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) [sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) [sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) [fabric-loader-0.16.2.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) [?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:473) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.1-loader.0.16.2-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.RuntimeException: Cannot load class net.frozenblock.wilderwild.mixin.client.indium.BlockRendererMixin in environment type SERVER
	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassBytes(KnotClassDelegate.java:433) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.getClassByteArray(Knot.java:318) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassBytes(MixinServiceKnot.java:60) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassNode(MixinServiceKnot.java:81) ~[fabric-loader-0.16.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1312) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:857) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	... 18 more
[13:07:17] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:71) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.21.1-loader.0.16.2-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.server.Main failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.2.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:473) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.2.jar:?]
	... 1 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [wilderwild.mixins.json:client.indium.BlockRendererMixin from mod wilderwild] from phase [DEFAULT] in config [wilderwild.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.2.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:473) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.2.jar:?]
	... 1 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Cannot load class net.frozenblock.wilderwild.mixin.client.indium.BlockRendererMixin in environment type SERVER
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:864) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:933) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:858) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.2.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:473) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.2.jar:?]
	... 1 more
Caused by: java.lang.RuntimeException: Cannot load class net.frozenblock.wilderwild.mixin.client.indium.BlockRendererMixin in environment type SERVER
	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassBytes(KnotClassDelegate.java:433) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.getClassByteArray(Knot.java:318) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassBytes(MixinServiceKnot.java:60) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassNode(MixinServiceKnot.java:81) ~[fabric-loader-0.16.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1312) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:857) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:933) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:858) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.2.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:473) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.2.jar:?]
	... 1 more

**Additional context**
Here I tried the 2.4.10 version but I tried the others and none were working.

**Comment by AViewFromTheEnd** [comment]
Bruhhhhhhhh

**Comment by AViewFromTheTop** [comment]
Fixed in future version 2.4.13.
