### ISSUE TITLE
Crashing/Timing out while loading certain chunks

### ISSUE THREAD

**Issue by TeaJeep** [FrozenBlock/WilderWild#421]
**Description of the Bug Encountered**
Random crashing/timeout, possibly caused by geyser block.

**Steps To Reproduce**
Unknown

**Logs**
Relevant section that leads me to Wilder Wilds:
java.lang.Error: Watchdog
	at java.base@18.0.1.1/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@18.0.1.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at net.minecraft.class_1255.method_20813(class_1255.java:521)
	at net.minecraft.class_1255.method_18857(class_1255.java:141)
	at net.minecraft.class_3215.getChunkBlocking(class_3215.java:1288)
	at net.minecraft.class_3215.method_12121(class_3215.java:1184)
	at net.minecraft.class_1937.method_8402(class_1937.java:204)
	at net.minecraft.class_1937.method_8497(class_1937.java:6559)
	at net.minecraft.class_1937.method_8320(class_1937.java:7051)
	at net.minecraft.class_1937.method_8455(class_1937.java:856)
	at net.minecraft.class_2586.method_31663(class_2586.java:155)
	at net.minecraft.class_2586.method_5431(class_2586.java:147)
	at net.frozenblock.wilderwild.block.entity.GeyserBlockEntity.tickServer(GeyserBlockEntity.java:119)
	at net.frozenblock.wilderwild.block.GeyserBlock.lambda$getTicker$0(GeyserBlock.java:197)
	at net.frozenblock.wilderwild.block.GeyserBlock$$Lambda$22656/0x000000080312ada0.tick(Unknown Source)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at net.minecraft.server.MinecraftServer$$Lambda$20020/0x0000000802d3da90.run(Unknown Source)
	at java.base@18.0.1.1/java.lang.Thread.run(Thread.java:833)

Full report here: [crash-2024-10-09_01.34.07-server.txt](https://github.com/user-attachments/files/17302683/crash-2024-10-09_01.34.07-server.txt)

**Additional context**

There are more mods installed, and have not had any problems up until now.  I have handled geyser blocks before, and found them many times, but I don't know what makes this different.  It has crashed while loading a specific region of the world several times now.

apologizes for the incomplete title, I accidentally hit enter, and then accidentally closed it while looking for an edit/delete option.

**Comment by AViewFromTheTop** [comment]
It’ll be a few weeks, but please wait for 3.0 to release. There’s a small chance it’s been fixed in one of the 1.21-only versions, which is of course getting backported alongside the 3.0 update.

**Comment by TeaJeep** [comment]
Will do, thank you!  Honestly it's the weirdest bug.  Been playing for weeks at this point, no issues, but a random chunk 7k blocks out causes a crash.

**Comment by AViewFromTheTop** [comment]
Has this been fixed?

**Comment by AViewFromTheTop** [comment]
Closing as no response has been given

**Comment by TeaJeep** [comment]
Apologies, haven't been logged into my personal GitHub account in a while- Just tested, and the issue has been fixed! Thank you!

**Comment by AViewFromTheTop** [comment]
HELL YEAH
