### ISSUE TITLE
Crash on startup when loaded alongside Pick Block Pro

### ISSUE THREAD

**Issue by FreyrDev** [FrozenBlock/WilderWild#430]
When trying to open the game with both [Pick Block Pro](https://github.com/Sjouwer/pick-block-pro) and Wilder Wild in the mods folder, it crashes before the window even appears. Modlist includes only these two mods and their dependencies. This is occuring on 1.21.1 with the latest release of both mods. I don't have a fabric install for 1.21.3 currently but I can check if needs be.

<details>
<summary>Log file</summary>

```
[13:49:06] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.7
[13:49:06] [main/INFO]: Loading 60 mods:
	- cloth-config 15.0.140
	   \-- cloth-basic-math 0.6.1
	- fabric-api 0.106.0+1.21.1
	   |-- fabric-api-base 0.4.42+6573ed8c19
	   |-- fabric-api-lookup-api-v1 1.6.68+b559734419
	   |-- fabric-biome-api-v1 13.0.29+5bd9f1bc19
	   |-- fabric-block-api-v1 1.0.22+0af3f5a719
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8c19
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a719
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8c19
	   |-- fabric-command-api-v1 1.2.49+f71b366f19
	   |-- fabric-command-api-v2 2.2.28+6ced4dd919
	   |-- fabric-commands-v0 0.2.66+df3654b319
	   |-- fabric-content-registries-v0 8.0.16+b559734419
	   |-- fabric-convention-tags-v1 2.1.0+7f945d5b19
	   |-- fabric-convention-tags-v2 2.9.0+83a9d31319
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a719
	   |-- fabric-data-attachment-api-v1 1.1.28+1daea21519
	   |-- fabric-data-generation-api-v1 20.2.21+16c4ae2519
	   |-- fabric-dimensions-v1 4.0.0+6fc22b9919
	   |-- fabric-entity-events-v1 1.7.0+2122d82819
	   |-- fabric-events-interaction-v0 0.7.13+ba9dae0619
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd919
	   |-- fabric-item-api-v1 11.1.0+d5debaed19
	   |-- fabric-item-group-api-v1 4.1.5+3fc0e55219
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a719
	   |-- fabric-keybindings-v0 0.2.45+df3654b319
	   |-- fabric-lifecycle-events-v1 2.3.12+6c1df36019
	   |-- fabric-loot-api-v2 3.0.14+3f89f5a519
	   |-- fabric-loot-api-v3 1.0.2+3f89f5a519
	   |-- fabric-message-api-v1 6.0.13+6573ed8c19
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6b19
	   |-- fabric-networking-api-v1 4.3.0+c7469b2119
	   |-- fabric-object-builder-api-v1 15.2.0+40875a9319
	   |-- fabric-particles-v1 4.0.2+6573ed8c19
	   |-- fabric-recipe-api-v1 5.0.13+6508971219
	   |-- fabric-registry-sync-v0 5.1.3+60c3209b19
	   |-- fabric-renderer-api-v1 3.4.0+c705a49c19
	   |-- fabric-renderer-indigo 1.7.0+c705a49c19
	   |-- fabric-renderer-registries-v1 3.2.68+df3654b319
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e19
	   |-- fabric-rendering-fluids-v1 3.1.6+1daea21519
	   |-- fabric-rendering-v0 1.1.71+df3654b319
	   |-- fabric-rendering-v1 5.0.5+df16efd019
	   |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b119
	   |-- fabric-resource-loader-v0 1.3.0+5659912919
	   |-- fabric-screen-api-v1 2.0.25+8b68f1c719
	   |-- fabric-screen-handler-api-v1 1.3.87+b559734419
	   |-- fabric-sound-api-v1 1.0.23+6573ed8c19
	   |-- fabric-transfer-api-v1 5.4.0+95bead5f19
	   \-- fabric-transitive-access-wideners-v1 6.1.0+1daea21519
	- fabricloader 0.16.7
	   \-- mixinextras 0.4.1
	- frozenlib 1.9.1-mc1.21.1
	- java 21
	- minecraft 1.21.1
	- modmenu 11.0.3
	   \-- placeholder-api 2.4.0-pre.2+1.21
	- pickblockpro 1.10.31
	- wilderwild 3.0.4-mc1.21.1
[13:49:06] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/home/hazel/.minecraft/libraries/net/fabricmc/sponge-mixin/0.15.3+mixin.0.8.7/sponge-mixin-0.15.3+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT
[13:49:06] [main/INFO]: Compatibility level set to JAVA_17
[13:49:06] [main/INFO]: Compatibility level set to JAVA_21
[13:49:07] [main/INFO]: Loading config WWMixinsConfig from wilderwild
[13:49:07] [main/INFO]: Saving config WWMixinsConfig from wilderwild
[13:49:08] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[13:49:09] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 291 milliseconds
[13:49:10] [main/INFO]: Loading config WWBlockConfig from wilderwild
[13:49:11] [main/INFO]: Saving config WWBlockConfig from wilderwild
[13:49:13] [main/INFO]: Loading config WWEntityConfig from wilderwild
[13:49:13] [main/INFO]: Saving config WWEntityConfig from wilderwild
[13:49:15] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[13:49:15] [Render thread/INFO]: Setting user: FreyrDev
[13:49:15] [Render thread/INFO]: Registering Particles for frozenlib
[13:49:16] [Render thread/INFO]: 0 Datafixer optimizations took 0 milliseconds
[13:49:16] [Render thread/INFO]: Loading config FrozenLibConfig from frozenlib
[13:49:16] [Render thread/INFO]: Saving config FrozenLibConfig from frozenlib
[13:49:16] [Render thread/INFO]: Applying Minecraft-Version-Based DataFixes for Wilder Wild with Data Version 3
[13:49:16] [FrozenLib Quilt Datafixer Bootstrap/INFO]: 2 Datafixer optimizations took 1 milliseconds
[13:49:16] [Render thread/INFO]: Minecraft-Version-Specific DataFixes for Wilder Wild have been applied
[13:49:16] [Render thread/INFO]: Applying DataFixes for Wilder Wild with Data Version 22
[13:49:16] [FrozenLib Quilt Datafixer Bootstrap/INFO]: 21 Datafixer optimizations took 2 milliseconds
[13:49:16] [Render thread/INFO]: DataFixes for Wilder Wild have been applied
[13:49:16] [Render thread/INFO]: Loading config WWAmbienceAndMiscConfig from wilderwild
[13:49:16] [Render thread/INFO]: Saving config WWAmbienceAndMiscConfig from wilderwild
[13:49:16] [Render thread/INFO]: Adding Music And Ambience To Biomes for wilderwild
[13:49:16] [Render thread/INFO]: Overriding Water Colors for wilderwild
[13:49:16] [Render thread/WARN]: Encountered duplicate API provider registration for block: wilderwild:stone_chest
[13:49:16] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[13:49:16] [Render thread/INFO]: Checking mod updates...
[13:49:17] [Render thread/INFO]: Loading config WWWorldgenConfig from wilderwild
[13:49:17] [Render thread/INFO]: Saving config WWWorldgenConfig from wilderwild
[13:49:17] [ModMenu/Update Checker/Fabric Loader/INFO]: Update available for 'fabricloader@0.16.7'
[13:49:17] [Worker-Main-1/INFO]: Update available for 'fabric-api@0.106.0+1.21.1', (-> 0.107.0+1.21.1)
```
</details>

<details>
<summary>Crash report</summary>

```---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-11-01 13:49:18
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'pickblockpro' at 'io.github.sjouwer.pickblockpro.PickBlockPro'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at knot//net.minecraft.class_310.<init>(class_310.java:477)
	at knot//net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: Errors during registry creation
	at knot//net.minecraft.class_7877$class_7878.method_46798(class_7877.java:186)
	at knot//net.minecraft.class_7877.method_46780(class_7877.java:332)
	at knot//net.minecraft.class_7887.method_46817(class_7887.java:108)
	at knot//io.github.sjouwer.pickblockpro.config.PickBlockOverrides.parseOverrides(PickBlockOverrides.java:69)
	at knot//io.github.sjouwer.pickblockpro.PickBlockPro.onInitializeClient(PickBlockPro.java:29)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:snowy_dying_forest]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:rainforest]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:snowy_dying_mixed_forest]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:sparse_birch_jungle]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:dark_taiga]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:warm_beach]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:warm_river]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:frozen_caves]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:dark_birch_forest]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:oasis]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:magmatic_caves]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:cypress_wetlands]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:maple_forest]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:birch_taiga]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:snowy_old_growth_pine_taiga]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:sparse_forest]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:dying_forest]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:parched_forest]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:old_growth_dark_forest]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:dying_mixed_forest]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:semi_birch_forest]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:birch_jungle]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:old_growth_birch_taiga]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:arid_savanna]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:mesoglea_caves]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:arid_forest]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:temperate_rainforest]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:flower_field]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more
	Suppressed: java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / wilderwild:mixed_forest]
		at knot//net.minecraft.class_7877$class_7878.method_55299(class_7877.java:180)
		at knot//net.minecraft.class_7877.method_46780(class_7877.java:330)
		... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at knot//net.minecraft.class_310.<init>(class_310.java:477)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at knot//net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Linux (amd64) version 6.9.3-76060903-generic
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 8284194640 bytes (7900 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600H with Radeon Graphics
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 4.28
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: GA106M [GeForce RTX 3060 Mobile / Max-Q]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MiB): 8224.00
	Graphics card #0 deviceId: 0x2560
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 27859.99
	Virtual memory used (MiB): 10800.58
	Swap memory total (MiB): 19938.49
	Swap memory used (MiB): 3499.34
	Space in storage for jna.tmpdir (MiB): available: 797776.63, total: 928723.38
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 797776.63, total: 928723.38
	Space in storage for io.netty.native.workdir (MiB): available: 797776.63, total: 928723.38
	Space in storage for java.io.tmpdir (MiB): available: 797776.63, total: 928723.38
	Space in storage for workdir (MiB): available: 797776.63, total: 928723.38
	JVM Flags: 9 total; -Xss1M -Xms8G -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		fabric-api: Fabric API 0.106.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bc19
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.0+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.0+83a9d31319
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.28+1daea21519
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.21+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.0+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.5+3fc0e55219
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df36019
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+5659912919
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.0+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabricloader: Fabric Loader 0.16.7
			mixinextras: MixinExtras 0.4.1
		frozenlib: FrozenLib 1.9.1-mc1.21.1
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21.1
		modmenu: Mod Menu 11.0.3
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		pickblockpro: Pick Block Pro 1.10.31
		wilderwild: Wilder Wild 3.0.4-mc1.21.1
	Launched Version: fabric-loader-0.16.7-1.21.1
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GFLW Platform: <error>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_GB
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: <unknown>
```
</details>

Reported to them as well: Sjouwer/pick-block-pro#35

**Comment by AViewFromTheTop** [comment]
Seems to be their issue as far as I can tell.
Would you be able to test with another biome mod?

**Comment by Treetrain1** [comment]
This is not our issue, but I provided information in the other issue report.
