### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ExDrill** [FrozenBlock/WilderWild#78]
```
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'wilderwild'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:443)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: net/lunade/copper/RegisterPipeNbtMethods$DispenseMethod
	at net.frozenblock.wilderwild.misc.mod_compat.simple_copper_pipes.RegisterSaveableMoveablePipeNbt.init(RegisterSaveableMoveablePipeNbt.java:27)
	at net.frozenblock.wilderwild.WilderWild.onInitialize(WilderWild.java:123)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.lunade.copper.RegisterPipeNbtMethods$DispenseMethod
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 10 more

```

**Comment by AViewFromTheTop** [comment]
Do you have Simple Copper Pipes installed? If so, you’ll need the latest version of 1.11.

**Comment by ExDrill** [comment]
That's the strange part, I do.

**Comment by MerpisMe** [comment]
any updates on this issue? is it still happening, @ExDrill?

**Comment by digitaltrucker** [comment]
I get the same crash with the latest version of Fabric API (0.60.0).  Reverting to version 0.59.0 of Fabric API resolves the crash problem.

I do not have simple copper pipes.

**Comment by MerpisMe** [comment]
> I get the same crash with the latest version of Fabric API (0.60.0). Reverting to version 0.59.0 of Fabric API resolves the crash problem.
> 
> I do not have simple copper pipes.

@Treetrain1

**Comment by AViewFromTheTop** [comment]
i knew the new fabric api sucked

**Comment by ExDrill** [comment]
> any updates on this issue? is it still happening, @ExDrill?

Well now I get this issue

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'supplementaries'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:443)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: java.lang.NoClassDefFoundError: net/lunade/copper/RegisterPipeNbtMethods$CanMoveMethod
		at net.frozenblock.wilderwild.misc.mod_compat.simple_copper_pipes.RegisterSaveableMoveablePipeNbt.init(RegisterSaveableMoveablePipeNbt.java:27)
		at net.frozenblock.wilderwild.WilderWild.onInitialize(WilderWild.java:123)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 7 more
	Caused by: java.lang.ClassNotFoundException: net.lunade.copper.RegisterPipeNbtMethods$CanMoveMethod
		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
		... 10 more
Caused by: java.lang.NoSuchMethodError: 'net.mehvahdjukaar.moonlight.api.misc.RegSupplier net.mehvahdjukaar.moonlight.api.platform.RegHelper.registerMenuType(net.minecraft.class_2960, net.mehvahdjukaar.moonlight.api.misc.TriFunction)'
	at net.mehvahdjukaar.supplementaries.reg.ModRegistry.<clinit>(ModRegistry.java:131)
	at net.mehvahdjukaar.supplementaries.Supplementaries.commonInit(Supplementaries.java:60)
	at net.mehvahdjukaar.supplementaries.fabric.SupplementariesFabric.onInitialize(SupplementariesFabric.java:23)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more
	```

**Comment by ExDrill** [comment]
Okay nevermind, this was due to an outdated mod, but the issue it still persisting with the same log.
